var LANG={
"":""
,"affiliate:acc:ahn":'帳號戶名'
,"affiliate:acc:ban":'銀行帳戶'
,"affiliate:acc:bc":'銀行代碼'
,"affiliate:acc:bn":'銀行名稱'
,"affiliate:acc:brn":'分行名稱'
,"affiliate:acc:c_info":'請款公司帳戶資訊'
,"affiliate:acc:err:ahn":'請輸入收款人戶名'
,"affiliate:acc:err:ahn3":'帳號戶名需與商業登記公司名稱一致'
,"affiliate:acc:err:ahn4":'請輸入收款公司戶名'
,"affiliate:acc:err:ahn:2":'帳號戶名需與身分證姓名一致'
,"affiliate:acc:err:ban":'請輸入收款銀行帳戶'
,"affiliate:acc:err:bc":'請輸入收款銀行代碼'
,"affiliate:acc:err:bn":'請輸入收款銀行名稱'
,"affiliate:acc:err:brn":'請輸入收款銀行分行名稱'
,"affiliate:acc:err:id":'請填寫證件號碼'
,"affiliate:acc:err:info":'請輸入提領帳戶資訊'
,"affiliate:acc:err:sc":'請輸入收款銀行 SWIFT Code'
,"affiliate:acc:err:tax_id":'請輸入公司統一編號'
,"affiliate:acc:info":'請款人帳戶資訊'
,"affiliate:acc:pp":'收款帳戶 PayPal Email'
,"affiliate:apply:err":'請填寫所有欄位'
,"affiliate:apply:err:agree":'請詳閱合作條款並勾選同意'
,"affiliate:apply:err:email":'請綁定Email並認證後再進行申請'
,"affiliate:apply:err:esign":'電子簽名不能為空'
,"affiliate:apply:err:existed":'您已申請聯盟行銷並在審核中，請稍待審核結果'
,"affiliate:apply:err:link":'請輸入有效連結'
,"affiliate:apply:err:social":'請至少輸入一個您的社群連結'
,"affiliate:apply:stop_failed":'感謝你申請加入 MacroMicro 聯盟行銷計劃，但基於多個因素，目前無法推進你的申請，再次感謝你對 MacroMicro 的興趣。'
,"affiliate:apply:success":'我們已收到您的申請，將在審核結果出來後通知您'
,"affiliate:dashboard:hint1":'使用專屬優惠碼訂閱的總人數'
,"affiliate:dashboard:hint2":'使用該優惠碼訂閱，訂閱後 90 天無退訂總人數'
,"affiliate:dashboard:hint3":'可提領金額 + 申請中金額 + 已提領金額'
,"affiliate:dashboard:hint4":'(90天無退訂人數 x 年繳訂閱費*0.30) - 已提領分潤\')'
,"affiliate:dashboard:hint5":'你申請提領的金額，並且尚未轉帳成功'
,"affiliate:dashboard:hint6":'你成功提領的金額'
,"affiliate:e_sign":'電子簽名'
,"affiliate:e_sign:clear":'清除'
,"affiliate:e_sign:hint":'請於下方空白處撰寫您的電子簽名。'
,"affiliate:promo_user_cnt":'優惠碼使用總人數'
,"affiliate:tax_id":'公司統一編號'
,"affiliate:upload":'上傳影像'
,"affiliate:upload:brc":'上傳商業登記證明'
,"affiliate:upload:err:brc":'請上傳商用登記證明'
,"affiliate:upload:err:id_back":'請上傳身份證反面影像'
,"affiliate:upload:err:id_front":'請上傳身份證正面影像'
,"affiliate:upload:err:invoice":'請上傳發票影像'
,"affiliate:upload:err:passport":'請上傳護照影像'
,"affiliate:upload:id_back":'上傳身分證反面'
,"affiliate:upload:id_front":'上傳身分證正面'
,"affiliate:upload:invoice":'上傳 Invoice'
,"affiliate:upload:invoice:tw":'上傳台灣發票'
,"affiliate:upload:limit":'每張大小不超過 5 MB，檔案類型限「JPEG」與「PNG」'
,"affiliate:upload:passport":'上傳護照'
,"affiliate:withdraw:amount":'提領金額'
,"affiliate:withdraw:apply":'執行提領'
,"affiliate:withdraw:apply:tip":'執行提領需填妥與上傳下方資料，申請提領成功後，我方將於每季 15~20 號（每年 1、4、7、10月）完成撥款至您提供的帳戶。'
,"affiliate:withdraw:info":'提領資訊'
,"affiliate:withdraw:methods":'收款方式'
,"affiliate:withdraw:received":'我們已收到您的提領申請，我方將於近一季的 15~20 號完成撥款至您的帳戶，並將發送撥款完成通知信給您，請耐心等候。'
,"affiliate:withdraw:req:twd":'達 NT$24,000 可執行提領，每次提領須自行負擔約 5%金流手續費。'
,"affiliate:withdraw:req:usd":'達 US$800 可執行提領，每次提領須自行負擔約 5%金流手續費。'
,"affiliate:withdraw:wire":'電匯'
,"affiliate:withdrawer":'請款人資訊'
,"affiliate:withdrawer:addr":'通訊地址'
,"affiliate:withdrawer:c_addr":'公司地址'
,"affiliate:withdrawer:c_name":'公司名稱'
,"affiliate:withdrawer:c_owner":'公司負責人'
,"affiliate:withdrawer:c_phone":'公司聯絡電話'
,"affiliate:withdrawer:id":'身份證號碼'
,"affiliate:withdrawer:name":'姓名'
,"affiliate:withdrawer:passport":'護照號碼'
,"affiliate:withdrawer:phone":'聯絡電話'
,"affiliate:withdrawer:social":'社群連結（請提供您預計曝光聯盟行銷專屬連結的位置）'
,"attr:eta-qtip":'下次更新時間: {eta_human}'
,"bookmark:add_chart":'加入圖表'
,"bookmark:add_chart:limit":'（最多圖表數為 30 張）'
,"bookmark:add_chart_success":'加入圖表成功'
,"bookmark:add_collection":'新增圖組'
,"bookmark:add_collection_failed":'新增圖組失敗, 請稍候再試'
,"bookmark:add_collection_success":'新增圖組成功'
,"bookmark:add_to_collection":'新增至圖組'
,"bookmark:already_in_collection":'此圖表已經在此圖組內'
,"bookmark:backtest:empty":'前往研究工具箱，開始製作回測圖表'
,"bookmark:backtest:empty:btn":'前往回測區製圖'
,"bookmark:cancel_share":'取消發表'
,"bookmark:chart":'圖表'
,"bookmark:chart:add:search:result":'總共有 {total} 張圖表, 您目前已選取 {selected} 張'
,"bookmark:chart:add:self-collection:cnt":'總共有 {total} 張圖表'
,"bookmark:chart:mobile:filter":'套用篩選'
,"bookmark:chart:mobile:filter:clear":'改為預設'
,"bookmark:chart:origin":'圖表來源'
,"bookmark:chart:search:result":'總共有 {total} 張符合條件的圖表'
,"bookmark:chart:tag:all":'所有圖表'
,"bookmark:charts:edit":'編輯圖表資訊'
,"bookmark:charts:edit:toolbox":'前往工具箱編輯'
,"bookmark:charts:empty":'點擊加入圖表，能快速收藏現有 MM 圖表'
,"bookmark:charts:last_update":'更新時間'
,"bookmark:charts:open":'放大'
,"bookmark:charts:remove":'刪除圖表'
,"bookmark:charts:sharing":'已發表'
,"bookmark:charts:sticky":'編輯瀏覽優先度'
,"bookmark:charts:sticky:high":'高'
,"bookmark:charts:view":'前往查看'
,"bookmark:charts:view:collection":'前往圖組查看'
,"bookmark:chart_already_selected":'此圖表已選取，請另選其他圖表'
,"bookmark:choose_from_chart":'請選擇圖表'
,"bookmark:choose_from_collection":'從自定義的圖組中選擇'
,"bookmark:collect":'圖組'
,"bookmark:collection":'圖組'
,"bookmark:collection:added":'已加入該圖組'
,"bookmark:collection:edit":'編輯圖組'
,"bookmark:collection:empty":'點擊新增圖組，能將您已收藏的圖表做圖組分類'
,"bookmark:collection:header":'圖組名稱|敘述|圖表數|分享給成員|操作'
,"bookmark:collection:member:empty":'目前尚未收藏其他會員自製圖組'
,"bookmark:collection:remove":'移除圖組'
,"bookmark:collection:remove:msg":'執行移除後，該圖組將消失'
,"bookmark:collection:self:limit":'立即升級訂閱會員，將能繼續新增%s'
,"bookmark:collection:self:limit:pop-up":'升級訂閱將可瀏覽所有自建圖組'
,"bookmark:collection:self:limit:title":'自定義圖組數已達 5 組上限'
,"bookmark:collection:shared:empty":'目前管理者尚未分享任何圖組給您'
,"bookmark:collection_already_selected":'此圖組已選取，請另選其他圖組'
,"bookmark:collection_category":'分類'
,"bookmark:collection_share":'分享給成員'
,"bookmark:collection_share:cancel":'取消分享給成員'
,"bookmark:collection_share:cancel:msg":'取消分享後，您的成員將無法看到此圖組'
,"bookmark:collection_share:msg":'執行分享後，您的成員都會看到此圖組'
,"bookmark:contain_special_ch":'名稱不得包含特殊字元'
,"bookmark:filter:all":'所有'
,"bookmark:filter:chart:empty":'找不到符合的圖表'
,"bookmark:get_data_failed":'取得資料失敗，請稍後再試'
,"bookmark:limit:chart:msg1":'您收藏的圖表數已超過 10 張，'
,"bookmark:limit:chart:msg2":'後將可繼續收藏圖表，並無限瀏覽總經圖表。'
,"bookmark:limit:chart:sub":'升級訂閱'
,"bookmark:limit:collection:msg1":'您建立的圖組數已達 5 組上限，'
,"bookmark:limit:collection:msg2":'後將可瀏覽所有自建圖組。'
,"bookmark:limit:msg":'立即升級訂閱會員，將享有無限收藏圖表的權限。'
,"bookmark:non-subscriber:sticky":'訂閱後才能使用此功能，'
,"bookmark:no_chart_included":'目前尚無任何圖表'
,"bookmark:no_chart_selected":'目前尚無選擇任何圖表'
,"bookmark:no_collection_chosen":'請選擇要加入的目標圖組'
,"bookmark:no_collection_includ":'無任何圖組'
,"bookmark:no_collection_included":'目前尚無任何圖組'
,"bookmark:no_collection_selected":'目前尚無選擇任何圖組'
,"bookmark:post":'文章'
,"bookmark:question:go":'前往MM知識圈'
,"bookmark:search:add:chart":'輸入關鍵字搜尋 MM 官方圖表'
,"bookmark:search:blog:example":'搜尋已收藏的文章'
,"bookmark:search:chart:empty":'找不到符合搜尋字詞的圖表，建議試試其他關鍵字搜尋'
,"bookmark:search:chart:example":'搜尋已收藏的圖表'
,"bookmark:search:collection:empty":'未分類圖表'
,"bookmark:search:collection:example":'搜尋已收藏的圖組'
,"bookmark:search:empty":'找不到符合的%s，建議試試其他關鍵字搜尋。'
,"bookmark:search:example":'輸入關鍵字搜尋標題，例如: 美國'
,"bookmark:search:filter:btn":'篩選器'
,"bookmark:search:industry-report:example":'搜尋收藏報告'
,"bookmark:search:question:empty":'瀏覽其它用戶的提問與回答'
,"bookmark:search:question:example":'搜尋已收藏的提問'
,"bookmark:search:result":'總共有 {total} 筆資料'
,"bookmark:search:selected":'項已選'
,"bookmark:search:share":'圖表發表'
,"bookmark:search:spotlight:example":'搜尋已收藏的關鍵圖表'
,"bookmark:search:sticky":'瀏覽優先度'
,"bookmark:selected:all":'全選'
,"bookmark:setting:index":'設為專屬首頁'
,"bookmark:setting:index:cancel":'是否要將我的儀表板-%s取消設為專屬首頁？'
,"bookmark:setting:index:pop":'可將此標籤頁設為專屬首頁，於下次登入時或點擊左上角 logo，將會自動導到此頁面。'
,"bookmark:setting:index:remove":'已成功設置為原本首頁'
,"bookmark:setting:index:set":'是否要將我的儀表板-%s設為專屬首頁？'
,"bookmark:setting:index:set:success":'已成功設置為專屬首頁'
,"bookmark:shared":'已發表'
,"bookmark:shared-chart":'我要發表'
,"bookmark:share_collection_failed":'分享圖組失敗'
,"bookmark:share_collection_success":'分享圖組成功'
,"bookmark:sort":'圖表排序'
,"bookmark:sort:collection":'圖組內自訂排序'
,"bookmark:sort:new_old":'收藏順序 (由新到舊)'
,"bookmark:sort:old_new":'收藏順序 (由舊到新)'
,"bookmark:sort:sticky":'瀏覽優先度順序（由高到低）'
,"bookmark:sort:updated":'更新日期 (由新到舊)'
,"bookmark:toolbox":'工具箱'
,"bookmark:unlike":'取消收藏'
,"bookmark:unshare_collection_failed":'取消分享圖組失敗'
,"bookmark:unshare_collection_success":'取消分享圖組成功'
,"bookmark:update_chart_success":'更新圖表成功'
,"bookmark:update_collection_success":'更新圖組成功'
,"bookmark:upgrade:view":'立即升級瀏覽'
,"bookmarks:add:chart:to":'至'
,"bookmarks:back-text:header":'名稱|回測期間|交易商品|報酬率|勝率|風險獲利比|凱利公式|夏普比率|操作'
,"bookmarks:charts:edit:label":'圖表名稱|圖表描述|您能於此將圖表做適當的圖組分類'
,"bookmarks:charts:empty:btn":'立即加入圖表'
,"bookmarks:charts:header":'圖表名稱|我建立的圖組分類|瀏覽優先度|圖表來源|作者|操作'
,"bookmarks:collection:empty:btn":'立即新增圖組'
,"bookmarks:collection:member":'其他會員自製圖組'
,"bookmarks:collection:mm":'MM官方圖組'
,"bookmarks:collection:self":'我建立的圖組'
,"bookmarks:collection:shared":'被分享的圖組'
,"bookmarks:delete_self_chart":'您確定要刪除這張自製圖表？'
,"bookmarks:industry-report:empty":'尚無報告'
,"bookmarks:industry-report:empty:btn":'前往獨家產業報告'
,"bookmarks:only_remove_shared":'是否要取消發表？'
,"bookmarks:only_remove_shared:success":'您的圖表已從用戶觀點移除'
,"bookmarks:post:empty":'前往 MM 部落格，開始收藏相關文章'
,"bookmarks:post:empty:btn":'前往 MM 部落格'
,"bookmarks:remove_shared":'這張圖已發表在「用戶觀點」，圖表刪除後將連同發表一起刪除，您確定要刪除？'
,"bookmarks:spotlight:empty":'前往關鍵圖表，開始收藏相關關鍵圖表'
,"bookmarks:spotlight:empty:btn":'前往關鍵圖表'
,"bookmarks:tips":'點選圖表右下「愛心」取消收藏 or 刪除自製圖表！'
,"bookmarks:unlike":'是否要取消收藏？'
,"bookmarks:unlike:back-test":'執行刪除後，該回測資訊將消失'
,"bookmarks:unlike:self-chart":'是否確認刪除此圖表？'
,"btn:add-now":'立即加入'
,"btn:go-read":'立即閱讀'
,"btn:subscribe-now":'立即訂閱'
,"build:timeline:one_item_least":'請選擇至少一個項目'
,"build:timeline:one_stat_least":'最少需要一個數據'
,"build:timeline:two_stats_most":'最多只能使用兩個數據'
,"builder-quote:starter-tip":'使用【新增】或【四則運算】選擇數據，繪製圖表，以比較數據或資產在一段時間內的漲跌幅趨勢。'
,"builder-return:starter-tip":'使用【新增】或【四則運算】選擇數據，繪製圖表，以比較資產在一段時間內的報酬率。'
,"builder-season:starter-tip":'使用【新增】或【四則運算】選擇數據、繪製單一數據在近幾年的季節性趨勢。'
,"builder:add":'新增'
,"builder:add_arithmetic":'新增四則運算'
,"builder:add_stat":'新增數據'
,"builder:add_stat_to_draw":'請新增數據以繪圖'
,"builder:aggn":'整合方式'
,"builder:aggn:avg":'平均'
,"builder:aggn:eop":'最後'
,"builder:aggn:sum":'加總'
,"builder:ai":'AI 指令'
,"builder:ai:delete":'確認刪除訊息？'
,"builder:ai:error:arithmetic":'若要使用 AI 指令，請先移除設定之四則運算'
,"builder:ai:error:const_m":'「m 值」須為有效常數'
,"builder:ai:error:int_n":'「n 值」需為整數'
,"builder:ai:error:positive_n":'「n 值」需為正整數'
,"builder:ai:error:positive_n2":'「n 值」需為大於 1 正整數'
,"builder:ai:hint1":'1. 無法進行四則運算。'
,"builder:ai:hint2":'2. 依數據多寡，執行時間約介於 30~50 秒間。'
,"builder:ai:hint3":'3. 使用 AI 指令後，可再手動新增、調整數據、底色與設定。'
,"builder:ai:input_hint":'輸入想畫的數據、時間，或調整圖表設定'
,"builder:ai:recommends":'推薦數據'
,"builder:ai:timeout":'系統回應過久，請稍後再試、或減少同時繪製的數據量'
,"builder:any":'任何'
,"builder:arithmetic":'四則運算'
,"builder:arithmetic:max_limit":'四則運算數據最多8筆為限'
,"builder:arith_aggn_missing":'請選擇整合方式'
,"builder:arith_freq_must_equal":'兩個數據頻率需相同'
,"builder:arith_method":'運算方式'
,"builder:bar:selected_tip":'提示：使用【新增】選擇數據，以繪製圖表'
,"builder:bar:sorting":'最新值排序'
,"builder:bar:sorting:tip":'啟用後將依照最新日期的數據呈現排序'
,"builder:bar:tip":'使用【新增】選擇數據、繪製圖表，以觀察同一數據不同時間的變化，或是不同數據間的差異。'
,"builder:base:format":'請輸入正確日期格式(YYYY-mm-dd)'
,"builder:bias:opn_n":'N值須介於1~250'
,"builder:btn:create-collection-tooltip":'需要先儲存，才能新增圖組'
,"builder:btn:create-return-chart":'製作報酬率圖表'
,"builder:btn:save":'儲存更新'
,"builder:btn:save-as":'另存新圖'
,"builder:cannot_add":'已達圖表上限，無法新增'
,"builder:category":'分類'
,"builder:chart:add":'儲存圖表'
,"builder:chart:area":'圖表地區'
,"builder:chart:save_as":'另存新圖表'
,"builder:chart:setting":'圖表設定'
,"builder:chart:title":'圖表標題'
,"builder:chart:type":'圖表類型'
,"builder:chart:type:bar":'橫式長條圖'
,"builder:chart:type:column":'直式長條圖'
,"builder:chart:type:line":'線形圖'
,"builder:chart:type:line2":'線形圖與時間軸'
,"builder:chart:type:quote_h":'橫式漲跌幅'
,"builder:chart:type:quote_v":'直式漲跌幅'
,"builder:chart:update":'更新圖表'
,"builder:chart_desc":'圖表敘述'
,"builder:choose:collection":'請選擇圖組'
,"builder:color":'顏色'
,"builder:column_chart":'柱狀圖'
,"builder:confirm:leave":'確定要離開此頁嗎？<br><br>離開此頁後，目前繪製的圖表將不會儲存，確定要離開嗎？'
,"builder:currency_inverse":'匯率反轉'
,"builder:currency_inverse_help":'匯率反轉可用來將既有匯率數據如【美元/日圓】反轉為【日圓/美元】以利比較'
,"builder:custom":'自訂'
,"builder:dashStyle":'線條樣式'
,"builder:dates:empty":'請填寫開始與結束日期'
,"builder:date_range":'時間區間'
,"builder:decimal:precision":'小數點位數'
,"builder:default:range":'圖表預設顯示區間'
,"builder:delete":'刪除'
,"builder:edit":'編輯'
,"builder:end_date":'結束日期'
,"builder:exceed:beyond":'已超過數據最新年限'
,"builder:exceed:earliest":'已超過數據最早年限'
,"builder:export:slide":'適合簡報製作'
,"builder:export_img":'圖片'
,"builder:fill_chart_title":'請輸入圖表名稱'
,"builder:freq":'頻率'
,"builder:freq:be_same":'所選數據頻率皆須相同'
,"builder:freq:D":'日'
,"builder:freq:H":'半年'
,"builder:freq:M":'月'
,"builder:freq:Q":'季'
,"builder:freq:unify":'統一頻率'
,"builder:freq:unify:confirm":'此功能會將所有數據對齊成最低頻數據的頻率， 確定執行嗎'
,"builder:freq:W":'週'
,"builder:freq:Y":'年'
,"builder:global":'全球'
,"builder:hide_cc":'隱藏貨幣'
,"builder:latest_values":'最新值'
,"builder:legal:expression":'請輸入正確運算公式'
,"builder:legal:expression2":'請輸入正確運算公式，如A+B'
,"builder:line:tip":'使用【新增】或【四則運算】選擇數據、繪製圖表，以觀察其趨勢與走向。'
,"builder:line_chart":'曲線圖'
,"builder:m:constant":'請輸入常數'
,"builder:m:integer":'請輸入有效m值'
,"builder:more_info":'詳細資訊'
,"builder:n:integer":'請輸入整數'
,"builder:n:valid":'請輸入有效n值'
,"builder:opn":'運算'
,"builder:opn:accu_return":'累積報酬(%)'
,"builder:opn:base":'與基期比較'
,"builder:opn:be_single_type":'此運算方法只適用於單一數據'
,"builder:opn:bias":'乖離率(n)'
,"builder:opn:ch1":'變動量(與去年同期)'
,"builder:opn:chg":'變動量(與前值)'
,"builder:opn:drawdown":'回撤幅度(n)'
,"builder:opn:lin":'原始數據'
,"builder:opn:linmc":'乘以常數(m)'
,"builder:opn:log":'自然對數 ln'
,"builder:opn:mva":'移動平均(n)'
,"builder:opn:mvstd":'移動標準差(n)'
,"builder:opn:mvz":'移動Z分數(n)'
,"builder:opn:pc1":'年增率(YoY%)'
,"builder:opn:pc1mc":'年增率(YoY%) x 常數(m)'
,"builder:opn:pch":'變動率(與前值)(%)'
,"builder:opn:pchmc":'變動率(與前值)(%) 乘以常數(m)'
,"builder:opn:rebound":'回升幅度(n)'
,"builder:opn:reciprocal":'倒數'
,"builder:opn:shift":'領先/落後(n)'
,"builder:opn:ypchmm":'年化變動率(與n月)(%)'
,"builder:opn_base":'基期'
,"builder:op_error":'操作錯誤，請重試'
,"builder:origin_freq":'原始頻率'
,"builder:origin_unit":'原始單位'
,"builder:quote:color":'漲跌顏色'
,"builder:quote:green_up":'綠漲紅跌'
,"builder:quote:opn:chg":'變動量'
,"builder:quote:opn:pch":'變動率'
,"builder:quote:red_up":'紅漲綠跌'
,"builder:return:only_assets":'報酬率圖只限制資產'
,"builder:save-new-chart-msg":'圖表已新增成功，可至「<a target="_blank" href="/user/dashboards">我的儀表板</a>」查看。'
,"builder:saved_share":'圖表已新增至<a target="_blank" href="/user/dashboards">我的儀表板</a>，點擊下一步進入「發表至用戶觀點」。'
,"builder:selected":'已選'
,"builder:selected_tip":'提示：使用【新增】或【四則運算】選擇數據，以繪製圖表'
,"builder:series:invalid":'此運算方式無法計算，請選擇其他方式'
,"builder:shaded":'底色'
,"builder:shaded:add":'新增底色'
,"builder:shaded:emtpy":'請填寫底線名稱'
,"builder:shaded:opacity":'透明度'
,"builder:share":'發表至用戶觀點'
,"builder:stacked:tip":'使用【新增】選擇數據、繪製圖表，以觀察多種數據堆疊後的趨勢與走向。'
,"builder:start_date":'開始日期'
,"builder:stat_country":'數據地區'
,"builder:stat_list":'數據項目'
,"builder:stat_list:placeholder":'輸入關鍵字搜尋'
,"builder:stat_name":'數據名稱'
,"builder:thickness":'線條粗細'
,"builder:timeline:cancel_all":'取消選取'
,"builder:timeline:selected_yet":'尚未選取事件'
,"builder:timeline:select_all":'全選'
,"builder:timeline:sort_by_event":'事件排序'
,"builder:timeline:sort_by_time":'時間排序'
,"builder:timeline:tab":'事件|數據|篩選'
,"builder:unify_y":'統一Y軸單位名稱'
,"builder:unit":'單位'
,"builder:unitlabel":'單位名稱'
,"builder:update":'更新'
,"builder:update_chart_success":'更新圖表成功'
,"builder:x_axis_baseline":'X軸臨界點'
,"builder:x_axis_baseline:tip":'非必填；多個可用半形逗號隔開,日期格式如: 2010-01-01'
,"builder:ybaselines_placeholder":'非必填；多個可用半形逗號隔開'
,"builder:y_axis:unitlabel":'Y軸單位名稱'
,"builder:y_axis:unit_changed":'Y軸設定已更新'
,"builder:y_axis_baseline":'Y軸臨界點'
,"builder:y_axis_left":'Y軸靠左'
,"builder:y_axis_level":'Y軸階層'
,"builder:y_axis_line":'線性Y軸'
,"builder:y_axis_log":'對數Y軸'
,"builder:y_axis_max":'Y軸高標值 (Max)'
,"builder:y_axis_min":'Y軸低標值 (Min)'
,"builder:y_axis_right":'Y軸靠右'
,"builder:y_axis_rotate":'Y軸翻轉'
,"calendar:btn:today":'今天'
,"calendar:earnings:note":'美股財報事件時間，依照美東時區 GMT-5 顯示。'
,"calendar:event:no":'無任何事件'
,"calendar:event:unit":'個事件'
,"calendar:holiday:note":'休市日依照之當地日期顯示，僅含官方公告之例行休市日，不包含天災、戰爭等臨時突發之休市安排。'
,"calendar:macro:note":'經濟事件時間，依照當前所在地之時區 GMT{num} 顯示。'
,"calendar:note":'資料以官方機構最終實際公布為準。'
,"cb:au:r_name":'現金利率'
,"cb:cn:r_name":'貸款市場報價利率[LPR]-1年期'
,"cb:core_cpi":'核心通膨'
,"cb:earth_op1":'基準利率'
,"cb:earth_op2":'近期升降息狀況'
,"cb:earth_title1":'最新利率'
,"cb:earth_title2":'一年變動'
,"cb:econ_index":'經濟指標'
,"cb:eu:r_name":'主要再融資利率'
,"cb:forever:text":'永久'
,"cb:gdp_forecasts":'經濟預測'
,"cb:inflation":'通膨'
,"cb:jin10:collapse":'收合'
,"cb:jin10:expand":'展開'
,"cb:last_change":'最後調整變動'
,"cb:last_change_on":'最後調整會議'
,"cb:last_m_date":'最新會議'
,"cb:main_title":'央行專區'
,"cb:mm_news":'M平方解讀'
,"cb:month":'月份'
,"cb:movement":'走勢'
,"cb:m_minutes":'會議紀要'
,"cb:m_of_meeting":'月會議'
,"cb:m_projection":'利率預估'
,"cb:na":'尚未公布'
,"cb:next_m_date":'下次會議'
,"cb:official_news":'官方新聞稿'
,"cb:policy_rates":'主要利率'
,"cb:policy_statement":'利率決議'
,"cb:position:centrist":'中立'
,"cb:position:dove":'鴿派'
,"cb:position:dovish":'偏鴿'
,"cb:position:hawk":'鷹派'
,"cb:position:hawkish":'偏鷹'
,"cb:prev":'前'
,"cb:quotes:today":'會議當日'
,"cb:quotes:total":'會議至今'
,"cb:rates":'利率'
,"cb:rates_projection":'下次利率預估'
,"cb:real_gdp":'實質GDP'
,"cb:r_bitmap":'利率點陣圖'
,"cb:title":'央行'
,"cb:tw:r_name":'重貼現率'
,"cb:unemploy_rate":'失業率'
,"cb:us:forerver:detail":'永久票委（聯邦理事會）'
,"cb:us:forever:detail":'永久票委(聯邦理事會)'
,"cb:us:r_name":'目標利率上限'
,"cb:us:yes:detail":'具投票權FOMC成員'
,"cb:voting:eu_members":'6 位執行委員'
,"cb:voting:name":'姓名'
,"cb:voting:photo":'照片'
,"cb:voting:position":'立場'
,"cb:voting:rights":'投票權'
,"cb:yes:text":'有'
,"cb:y_rate_forcast":'全年利率預估'
,"chart:blocked:msg":'此為 MM Max 年繳訂閱專屬，現在加入終身享早鳥最低價'
,"chart:blocked:msg:1":'此為 MM Max 訂閱專屬，現在加入終身享早鳥最低價'
,"chart:blocked:msg:2":'此內容僅限專屬訂閱方案之會員閱讀'
,"chart:btn:enlarge":'放大'
,"chart:btn:share":'分享圖表'
,"chart:btn:shrink":'縮小'
,"chart:btn:shrink-and-enlarge":'放大與縮小'
,"chart:change_range":'切換時間'
,"chart:export:source":'資料來源：MacroMicro 財經M平方'
,"chart:feature:biz_only:hint":'升級 MM Business 方案解鎖專屬功能'
,"chart:feature:high_low":'最高與最低值'
,"chart:label:also-viewed":'其他人也看了'
,"chart:label:latest-stats":'最新數據'
,"chart:label:source":'資料來源'
,"chart:latest:upgrade":'升級 MM Business 方案，解鎖匯出時含最新值功能，<a target="_blank" class="latest-value-biz-contact" href="/subscribe#modal-biz-contact">立即聯絡專員了解</a>'
,"chart:limit:normal":'立即成為訂閱會員享全站總經圖表無限瀏覽。'
,"chart:limit:title":'您的圖表免費瀏覽額度快達上限了'
,"chart:limit:unlogin":'立即成為免費一般會員看更多，或升級為訂閱會員享全站總經圖表無限瀏覽。'
,"chart:plotbands:tip1":'圖中灰色區塊，是財經M平方根據美國全國經濟研究院（NBER）標注的衰退時點，全球的專業機構均會參考他們提供的資訊，相關連結 <a target="_blank" href="https://www.nber.org/research/business-cycle-dating">請點此</a>'
,"chart:plotbands:tip2":'圖中如有其他顏色區塊，則是財經M平方研究員針對個別數據，標註的事件與時間段，詳情可參考此圖表右方註解說明。'
,"chart:stat:full_stop":'該圖表數據已停更'
,"chart:stat:partial_stop":'該圖表部分數據已停更'
,"chart:stat:stop_update":'停更'
,"chart:title:rel-articles":'相關文章'
,"chart:title:related_charts":'相關圖表'
,"chart:title:related_collections":'相關圖組'
,"chart:title:viewed_charts":'其他人也看了'
,"chart:toggle_series":'數據全選'
,"chart:user-chart-subtitle":'MacroMicro.me | by {user.name}'
,"chart:user:title":'圖表作者'
,"chart:watermark:upgrade":'升級 MM Business 方案，將能匯出無浮水印與呈現最新值版本的圖表，<a target="_blank" class="export-biz-contact" href="/subscribe#modal-biz-contact">立即聯絡專員了解</a>'
,"chart:watermark:upgrade2":'升級 MM Business 方案，將能解鎖去除浮水印功能，<a target="_blank" class="watermark-biz-contact" href="/subscribe#modal-biz-contact">立即聯絡專員了解</a>'
,"collection:msg:overload":'僅顯示前 30 張圖表，<a href="?showall=1">是否完整顯示 {charts} 張圖表</a>? (將需等待較久時間)'
,"comment:badge:unmoderated":'未審核'
,"comment:btn:replies":'則回覆'
,"comment:btn:reply":'回覆'
,"comment:btn:replying-to":'正在回覆'
,"comment:btn:submit":'發佈'
,"comment:msg:must-login-before-commenting":'需登入後方能進行留言'
,"comment:placeholder:default":'請輸入至少10個字'
,"common:abs":'絕對值'
,"common:added":'已加入'
,"common:ai_def":'AI 註解'
,"common:badge:membersonly":'訂閱會員限定'
,"common:badge:membersonly-pro":'PRO 限定'
,"common:browser_not_support":'您的瀏覽器不支援此功能，請更換為Chrome或Edge瀏覽器'
,"common:btn:add":'新增'
,"common:btn:back_home":'返回首頁'
,"common:btn:bookmark":'收藏'
,"common:btn:cancel":'取消'
,"common:btn:copy-link":'複製連結'
,"common:btn:delete":'刪除'
,"common:btn:download":'下載'
,"common:btn:download:size":'尺寸'
,"common:btn:follow":'追蹤'
,"common:btn:following":'追蹤中'
,"common:btn:go":'立即前往'
,"common:btn:login":'登入'
,"common:btn:login2":'登入註冊'
,"common:btn:more":'看更多'
,"common:btn:next":'下一步'
,"common:btn:prev":'前一步'
,"common:btn:redeem":'兌換'
,"common:btn:share":'分享'
,"common:btn:sign-up-log-in":'立即註冊登入'
,"common:btn:start_subscribe":'開始訂閱'
,"common:btn:submit":'送出'
,"common:btn:subscribe":'前往訂閱'
,"common:btn:subscribe2":'升級訂閱'
,"common:btn:subscribe3":'一鍵升級'
,"common:btn:sure":'確認'
,"common:btn:to-login":'前往登入'
,"common:btn:understand":'了解'
,"common:btn:update":'更新'
,"common:btn:upgrade":'升級 MM Prime'
,"common:btn:upgrade-to-sub":'前往升級訂閱'
,"common:btn:upgrade:plan":'升級方案'
,"common:btn:watch":'查看'
,"common:coming-soon":'即將推出'
,"common:comment:msg:successfully-added":'謝謝你的留言'
,"common:label:comments":'討論'
,"common:label:rel-etf":'相關ETF'
,"common:label:rel-etf:1m":'1個月'
,"common:label:rel-etf:expense-ratio":'總管理費'
,"common:label:rel-etf:name":'投資標的'
,"common:label:rel-etf:price":'價格'
,"common:label:rel-etf:ytd":'年初至今'
,"common:label:suggest":'建議與回饋'
,"common:label:suggest:placeholder":'歡迎給我們回饋！'
,"common:loading":'載入圖表中...'
,"common:modal-bookmark-collection:success":'已成功將圖表加入圖組內'
,"common:msg:invalid-request":'無法執行'
,"common:none":'無'
,"common:others":'其他'
,"common:prompt:paging":'請輸入欲前往頁數 (1~{pages})'
,"common:ratio":'佔比'
,"common:search:selected":'項已選'
,"common:selected:all":'全選'
,"cot:basic_metals:title":'基本金屬'
,"cot:col_bear":'看空'
,"cot:col_bull":'看多'
,"cot:col_name":'名稱'
,"cot:energy:title":'能源'
,"cot:grains:title":'穀物'
,"cot:livestock:title":'畜牧'
,"cot:long_term":'趨勢'
,"cot:precious_metals:title":'貴金屬'
,"cot:prod:brent":'布蘭特原油'
,"cot:prod:coarse_rice":'粗米'
,"cot:prod:cocoa":'可可'
,"cot:prod:coffee":'咖啡'
,"cot:prod:corn":'玉米'
,"cot:prod:cotton":'棉花'
,"cot:prod:feeder_cattle":'育肥牛'
,"cot:prod:gas":'天然氣'
,"cot:prod:gasoline":'汽油'
,"cot:prod:gas_oil":'倫敦柴油'
,"cot:prod:gold":'黃金'
,"cot:prod:ho":'熱燃油'
,"cot:prod:hog":'瘦豬'
,"cot:prod:live_cattle":'活牛'
,"cot:prod:LME_aluminum":'LME 鋁'
,"cot:prod:LME_copper":'LME 銅'
,"cot:prod:LME_lead":'LME 鉛'
,"cot:prod:LME_nickle":'LME 鎳'
,"cot:prod:LME_tin":'LME 錫'
,"cot:prod:LME_zinc":'LME 鋅'
,"cot:prod:NYMEX_copper":'NYMEX 銅'
,"cot:prod:oat":'燕麥'
,"cot:prod:orange_juice":'橙汁'
,"cot:prod:palladium":'鈀金'
,"cot:prod:platinum":'鉑金'
,"cot:prod:silver":'白銀'
,"cot:prod:soybean":'黃豆'
,"cot:prod:soybean_oil":'黃豆油'
,"cot:prod:sugar":'原糖'
,"cot:prod:wheat":'小麥'
,"cot:prod:wood":'木材'
,"cot:prod:wti":'西德州原油'
,"cot:short_term":'一週'
,"cot:softs:title":'軟性商品'
,"country:continent:1":'撒哈拉以南非洲'
,"country:continent:2":'中東與北非'
,"country:continent:3":'西歐與中歐'
,"country:continent:4":'東歐與中亞'
,"country:continent:5":'亞太地區'
,"country:continent:6":'拉丁美洲'
,"country:continent:7":'北美洲'
,"country:continent:africa":'非洲'
,"country:continent:america":'美洲'
,"country:continent:asia":'亞洲'
,"country:continent:europe":'歐洲'
,"country:continent:oceania":'大洋洲'
,"created:sort:new:old":'發表日期（新到舊）'
,"created:sort:old:new":'發表日期（由舊到新）'
,"cross:check-box:error:msg":'請勾選國家數據'
,"cross:country:developed":'成熟國家'
,"cross:country:ema":'新興亞洲'
,"cross:country:eme":'新興國家'
,"cross:date:error:msg":'起始日期時間不可大於結束日期'
,"cross:date:error:year:msg":'起始日期與結束日期不可大於 {year} 年'
,"cross:no:country":'無任何國家'
,"cross:top-chart:update":'上方圖表已更新'
,"crypto:desc:1":'加密貨幣數量成千上萬個，此處列出市值前幾大的幣種，包含龍頭的比特幣、以太幣和各類平台幣。由於區塊鏈技術更新迭代，應用推陳出新，因此每種加密貨幣提供的功能不盡相同，也保持一定程度的競爭關係。<br><br>註：幣種陳列將每兩週隨市值變化更新'
,"crypto:desc:2":'平台幣是由加密資產交易平台官方發行的加密貨幣，平台幣普遍的功能在於優惠折抵平台交易手續費、去中心鏈交易的運算手續費（Gas Fee）、其他平台相關權益服務等。此外，平台幣也會明定一定的獎勵／銷毀機制，以賦予該平台幣一定的價值。'
,"crypto:desc:3":'Defi（Decentralized Finance）去中心化金融，透過在區塊鏈建構包含特定邏輯應用的智能合約，實現無中心營運機構的去中心化金融服務，例如資金借貸、衍生品、貨幣交易等。<br><br>Defi 平台通常會發行其特有代幣，並授與代幣特定功能及獎勵分配機制，賦予該代幣一定價值，稱為 Defi 幣。例如，去中心化借貸平台的 Compound 發行的 COMP，其分配機制包含獎勵資金借貸雙方可獲得一定數量的 COMP ，做為促進 Defi 平台資金承貸量的手段。'
,"crypto:desc:4":'穩定幣被設計為與某些法定貨幣或商品的價值相連接，從而保持其穩定性。目前穩定幣大多以美元穩定幣為主，每 1 個美元穩定幣維持在 1 美元的價格。<br>穩定幣不易波動，因此適合作為加密貨幣資產交易的媒介，節省法幣與加密貨幣轉換的成本。'
,"datepicker:placeholder":'選擇時間'
,"developed_countries":'先進國家'
,"developing_countries":'新興國家'
,"dnb:country:select":'選擇經濟體'
,"dnb:country:select:error":'請選擇經濟體'
,"dnb:crr:map:data:title":'國家風險評級'
,"dnb:esg:map:data:title":'量化表現'
,"dnb:global":'全球'
,"dnb:industry:sectors":'產業分類'
,"dnb:map:high-risk":'高風險'
,"dnb:map:highest-risk":'最高風險'
,"dnb:map:low-risk":'低風險'
,"dnb:map:lowest-risk":'最低風險'
,"dnb:map:moderate-risk":'中風險'
,"dnb:map:slight-risk":'稍有風險'
,"dnb:map:very-high-risk":'非常高風險'
,"dnb:srr:map:data:title":'產業風險評級'
,"download:chart:title":'匯出圖表 (png)'
,"dynamic_chart:alert:to:other":'若要瀏覽該圖表，請前往國家數據中心瀏覽'
,"dynamic_chart:season:desc":'圖表說明'
,"edm:non-pro-monthly-report-purchase":'你也可以用Ｍ幣購買最新一期月報，<a href="/user/mcoins">點我購買</a>'
,"etc:under_construct":'建置中，即將上線'
,"etf:10y":'10年'
,"etf:15y":'15年'
,"etf:1d":'1日'
,"etf:1m":'1個月'
,"etf:1w":'1週'
,"etf:1y":'1年'
,"etf:2y":'2年'
,"etf:3m":'3個月'
,"etf:3y":'3年'
,"etf:5y":'5年'
,"etf:6m":'6個月'
,"etf:account_currency":'計價貨幣'
,"etf:accu_return":'累計報酬'
,"etf:actively_managed":'主動'
,"etf:active_passive":'主動/被動'
,"etf:all":'全部'
,"etf:alternatives":'另類資產類型'
,"etf:analysis":'基本面'
,"etf:aum":'資產規模'
,"etf:aum:million":'資產規模(百萬)'
,"etf:aum:million2":'資產規模(百萬)'
,"etf:avg_duration":'平均存續期間(年)'
,"etf:avg_maturity":'平均到期期間(年)'
,"etf:bbg_exchange":'上市交易所'
,"etf:benchmark_index":'追蹤指數'
,"etf:benchmark_index_keyword":'請輸入關鍵字以搜尋追蹤指數'
,"etf:bond:duration":'債券期限'
,"etf:bond:region":'債券地區'
,"etf:bond:sector":'債券產業'
,"etf:bond:type":'債券種類'
,"etf:choose_freq":'請選取..'
,"etf:close":'市價'
,"etf:commodity":'原物料'
,"etf:commodity:exposure":'原物料風險'
,"etf:compare":'比較 ETF'
,"etf:compare:accu_chart":'累積圖'
,"etf:compare:accu_netflow":'累積資金淨流量'
,"etf:compare:accu_return":'累積報酬'
,"etf:compare:add_hint":'請選擇一個ETF以新增'
,"etf:compare:condition":'請勾選 2 ~ 4 檔 ETF 以進行比較'
,"etf:compare:count_limit":'一次最多只能比較四支ETF'
,"etf:compare:duplicate":'此ETF已在比較列表中'
,"etf:compare:full_compare":'完整比較'
,"etf:compare:text":'比較'
,"etf:corr":'美股大盤相關性'
,"etf:corr_10y":'10年大盤相關性'
,"etf:corr_15y":'15年大盤相關性'
,"etf:corr_1y":'1年大盤相關性'
,"etf:corr_5y":'5年大盤相關性'
,"etf:currency":'外匯'
,"etf:currency:original":'原始幣值'
,"etf:currency:twd":'新台幣'
,"etf:currency:usd":'美元'
,"etf:daily_change":'日變動'
,"etf:daily_dp_ratio":'每日折溢價'
,"etf:deviation:5y_return":'近五年累積'
,"etf:deviation:benchmark_return":'追蹤指數報酬'
,"etf:discount":'折價'
,"etf:dividend":'每股股利​'
,"etf:dp_ratio":'折溢價'
,"etf:drawdown":'期間最大回撤'
,"etf:drawdown_10y":'10年最大回撤'
,"etf:drawdown_15y":'15年最大回撤'
,"etf:drawdown_1y":'1年最大回撤'
,"etf:drawdown_5y":'5年最大回撤'
,"etf:equity:region":'股票地區'
,"etf:equity:sector":'股票產業'
,"etf:equity:size":'股票資產規模'
,"etf:equity:style":'股票資產類型'
,"etf:expense_ratio":'總管理費'
,"etf:full_name":'完整名稱'
,"etf:hint:active":'【主動型 ETF】由基金經理人負責操盤、依據市況決定成分股，目標為追求超額報酬，並不模擬指數績效。目前台灣主管機關尚未開放主動型 ETF，因此所有在台灣上市上櫃的 ETF 均屬於被動型。'
,"etf:hint:aum":'【資產規模】ETF 基金規模，衡量 ETF 管理資產的總市值，計算方式：淨值 * 在外流通股數。'
,"etf:hint:benchmark_index":'【追蹤指數】被動型 ETF 追蹤、模擬、複製表現的指數。​​'
,"etf:hint:close":'【市價】ETF 每日收盤價格'
,"etf:hint:corr":'【美股大盤相關性】衡量 ETF 和大盤報酬變化的相關係數，計算方式：ETF 與 S&P 500 指數日報酬的相關係數。相關係數的值介於 -1 ~ 1 之間，當絕對數值愈高，表示相關性愈高；而當相關係數 > 0，代表兩者報酬多為同向變化，< 0 則多為反向變化。​'
,"etf:hint:dp_ratio":'【折溢價】ETF 交易價格與淨值的差距比率，計算方式：市價 / 淨值。折溢價 > 0，表示 ETF 被高估，< 0 則表示被低估。'
,"etf:hint:drawdown":'【期間最大回撤】衡量 ETF 在期間內價格從最高點回檔的最大幅度，代表 ETF 可能的最大虧損。​'
,"etf:hint:expense_ratio":'【總管理費】資料來源為投信投顧公會公佈之 ETF 去年全年總管理費率。包含交易直接成本（手續費、交易稅）、會計帳列費用（經理費、保管費、保證費、其他）。'
,"etf:hint:inverse":'【反向】代表目標為追蹤指數單日反向收益的 ETF。但須注意長期報酬並非追蹤指數反向收益。​'
,"etf:hint:leveraged":'【槓桿】代表目標為放大追蹤指數單日收益倍數的 ETF。但須注意長期報酬並非追蹤指數收益倍數。​'
,"etf:hint:mdd":'【回撤曲線】衡量 ETF 價格相比歷史前高點回檔的幅度，計算方式：當日市價 / 歷史最高市價 - 1。'
,"etf:hint:nav":'【淨值】ETF 實際價值，計算方式：ETF 持有資產的實際價值 / 在外流通股數。也是 ETF 在初級市場申購贖回交易的執行價格。'
,"etf:hint:netflow":'【資金淨流量】 ETF 在初級市場申購贖回所產生的資金流向淨額，並不考慮 ETF 價格漲跌所造成的影響，可藉此觀察該檔 ETF 的需求以及市場情緒變化。計算方式：流通股數變化量 * 淨值。 ​'
,"etf:hint:passive":'【被動型 ETF】基金經理人不負責選股，而是隨指數成份股更動而調整投資組合，目標為追蹤標的指數的表現。目前台灣主管機關尚未開放主動型 ETF，因此所有在台灣上市上櫃的 ETF 均屬於被動型。'
,"etf:hint:replication_strategy":'【指數複製方法】​​<br>合成複製法 — ETF 透過金融衍生性商品複製指數報酬，不直接持有成分的現貨，會有流動性風險以及交易對手風險。​​<br>​​<br>完全複製法 — ETF 持有該指數 90% 或以上的成分，完全複製追蹤指數的成分以及權重，較能貼合追蹤指數績效，缺點是有較高的交易成本。<br>​​<br>最佳化複製法 — ETF 持有該指數的代表性樣本，涵蓋少於指數 90% 的成分，建構一個與追蹤指數類似的投資組合，能降低交易成本，缺點是與追蹤指數的績效差距容易較大。​​<br>​​<br>不適用 — 主動型 ETF 多數無追蹤指數 ，因此被分類為「不適用」。'
,"etf:hint:return_dividend":'【配息報酬】ETF 配息並且再投入所獲得的報酬。'
,"etf:hint:return_normal":'【資本利得】ETF 價格變化所產生的報酬，並不考慮配息所得。'
,"etf:hint:return_total":'【總報酬】持有 ETF 實際總報酬。計算方式：資本利得 + 配息報酬。​'
,"etf:hint:return_yearized":'【期間報酬（年化）】衡量 ETF 的每年平均報酬。'
,"etf:hint:risk_rank":'【風險等級】由投信投顧公會公佈，風險由低到高排序為 RR1、RR2、RR3、RR4、RR5 五個等級。<br><br>參考標準包含 ETF 的類型、投資區域或主要投資標的 / 產業。例如投資越多新興市場、店頭市場股票的 ETF，風險等級就會越高；投資越多成熟市場投資級債券或政府公債的 ETF，風險等級就會越低。<br><br><span class=\'text-danger\'>註：僅台灣發行的 ETF 有此資訊</span>'
,"etf:hint:sharpe_ratio":'【夏普比率（Sharpe ratio）】衡量投資者承擔每一單位風險所獲得的額外收益。計算方式：（扣除無風險利率後的 ETF 平均報酬）/ ETF 標準差。夏普比率越高，代表在同樣風險下能獲得的額外收益越高。​'
,"etf:hint:std_yearized":'【年化標準差】衡量 ETF 的每年價格平均波動程度。年化標準差越高，價格波動越劇烈。​'
,"etf:hint:tracked_error":'【追蹤誤差】 由於 ETF 的追蹤工具、操作策略、匯率變動、配息等因素，導致追蹤指數報酬和實際 ETF 報酬的差距。追蹤誤差越小，代表 ETF 越貼近追蹤指數報酬。追蹤誤差均以計價貨幣報酬計算。'
,"etf:hint:yearly_yield":'【年化殖利率】ETF 每年配息所佔價格的比率。計算方式：一年內所有配息的殖利率相乘。須注意年化殖利率越高，並不保證未來報酬越高。<br><br>例如假設ETF一年內配息 2 次，每次殖利率分別為 1% 和 2%。<br>1.01*1.02=1.0302 → 年化殖利率為 3.02%。'
,"etf:hint:yield":'【殖利率】ETF 每次配息所占價格的比率。計算方式：配息金額 / 配息前一個工作天價格。須注意殖利率越高，並不保證未來報酬越高。'
,"etf:hot_filter":'主題式篩選'
,"etf:hot_search":'熱門搜尋'
,"etf:inception":'發行年份'
,"etf:inception2":'發行日期'
,"etf:intro:3y_return":'三年報酬'
,"etf:intro:analysis":'基本面分析'
,"etf:intro:basic":'基本資料'
,"etf:intro:daily_return":'日報酬'
,"etf:intro:deviation_dp":'誤差與折溢價'
,"etf:intro:dividend":'配息'
,"etf:intro:dividend_yield":'股利與殖利率'
,"etf:intro:holdings":'持倉'
,"etf:intro:holding_country":'國家佔比'
,"etf:intro:holding_maturity":'債券期限'
,"etf:intro:holding_rating":'債券評等'
,"etf:intro:holding_sector":'產業佔比'
,"etf:intro:last_price":'最新市價'
,"etf:intro:last_update":'更新時間'
,"etf:intro:latest_date":'最新日期'
,"etf:intro:monthly_return":'月報酬'
,"etf:intro:netflow":'資金淨流量'
,"etf:intro:performance":'績效表現'
,"etf:intro:price":'價格圖'
,"etf:intro:return":'報酬'
,"etf:intro:risk_return":'風險報酬比較'
,"etf:intro:top10":'Top10持倉'
,"etf:intro:weekly_return":'週報酬'
,"etf:intro:yearly_return":'年報酬'
,"etf:inverse":'反向'
,"etf:inverse_leveraged":'反向/槓桿'
,"etf:issuer":'發行商'
,"etf:keyword":'關鍵字'
,"etf:last_aum":'AUM'
,"etf:last_close":'最新市價'
,"etf:last_number_of_holdings":'持股家數'
,"etf:leveraged":'槓桿'
,"etf:listed_type":'上市/上櫃交易所'
,"etf:mdd":'回撤曲線'
,"etf:mdd2":'回撤幅度'
,"etf:million":'百萬'
,"etf:name":'ETF名稱'
,"etf:nav":'淨值'
,"etf:netflow_3y":'3年資金淨流量'
,"etf:netflow_5y":'5年資金淨流量'
,"etf:netflow_monthly":'月資金淨流量'
,"etf:netflow_weekly":'週資金淨流量'
,"etf:netflow_yearly":'1年資金淨流量'
,"etf:netflow_ytd":'YTD資金淨流量'
,"etf:no":'否'
,"etf:passive":'被動'
,"etf:performance_chart":'績效圖'
,"etf:premium":'溢價'
,"etf:price":'價格'
,"etf:ratio":'佔比'
,"etf:regulatory_structure":'發行結構'
,"etf:related:return_yearized":'期間報酬(年化)'
,"etf:related_video":'影音課程'
,"etf:release-info":'發行資訊'
,"etf:replication_strategy":'指數複製方法'
,"etf:return":'報酬率'
,"etf:return:collapse":'收合績效圖'
,"etf:return:dividend":'配息報酬'
,"etf:return:normal":'資本利得'
,"etf:return:total":'總報酬'
,"etf:return:unfold":'展開績效圖'
,"etf:return_empty":'此區間無資料'
,"etf:risk_index":'風險指標'
,"etf:risk_rank":'風險等級'
,"etf:rows_not_found":'無篩選結果，請重設條件。'
,"etf:screener:asset_class_size":'規模'
,"etf:screener:asset_class_style":'風格'
,"etf:screener:at_least_one":'請至少加入一筆ETF進行比較'
,"etf:screener:at_most_ten":'最多只能加入十筆ETF進行比較'
,"etf:screener:bond_duration":'存續期間'
,"etf:screener:bond_type":'債券種類'
,"etf:screener:clear":'清除'
,"etf:screener:click_show":'請於「篩選結果 > 總覽 > 績效圖」勾選ETF，以觀察績效表現'
,"etf:screener:commodity_exposure":'操作標的'
,"etf:screener:commodity_type":'商品種類'
,"etf:screener:error":'發生錯誤，請重新讀取頁面'
,"etf:screener:leveraged_inverse":'槓桿/反向'
,"etf:screener:region":'區域'
,"etf:screener:reset_filter":'重新篩選'
,"etf:screener:result":'篩選結果'
,"etf:screener:sector":'產業'
,"etf:screener:select":'選取'
,"etf:screener:tw":'台灣'
,"etf:screener:zacks_category":'資產類別'
,"etf:search":'搜尋 ETF'
,"etf:search_hint":'請選擇一筆ETF數據進行搜尋'
,"etf:search_hint2":'請輸入ETF代碼或者搜尋名稱'
,"etf:series:accu":'累計'
,"etf:shares":'流通股數'
,"etf:sharpe_ratio":'夏普比率'
,"etf:sharpe_ratio_10y":'10年Sharpe Ratio'
,"etf:sharpe_ratio_15y":'15年Sharpe Ratio'
,"etf:sharpe_ratio_1y":'1年Sharpe Ratio'
,"etf:sharpe_ratio_5y":'5年Sharpe Ratio'
,"etf:show_all":'取消已選'
,"etf:std_yearized":'年化標準差'
,"etf:std_yearized_10y":'10年化標準差'
,"etf:std_yearized_15y":'15年化標準差'
,"etf:std_yearized_1y":'1年化標準差'
,"etf:std_yearized_5y":'5年化標準差'
,"etf:stock:keyword":'輸入個股關鍵字'
,"etf:stock:search":'個股反查 ETF'
,"etf:stock:search_limit":'請最少選取一筆、最多選取四筆個股進行搜尋。'
,"etf:stock_exchange":'上市/上櫃交易所'
,"etf:table:basic":'總覽'
,"etf:tag":'標籤'
,"etf:thousand":'千'
,"etf:threshold":'門檻值'
,"etf:ticker":'代碼'
,"etf:topics":'主題/因子'
,"etf:total_return_3m":'三個月報酬率'
,"etf:total_return_3y":'三年報酬率'
,"etf:total_return_5y":'5年報酬率'
,"etf:total_return_daily":'日報酬率'
,"etf:total_return_monthly":'月報酬率'
,"etf:total_return_weekly":'週報酬率'
,"etf:total_return_yearly":'1年報酬率'
,"etf:total_return_ytd":'YTD報酬率'
,"etf:tracked_error":'追蹤誤差'
,"etf:trading":'交易數據'
,"etf:tutorial_post":'教學文章'
,"etf:volume":'交易量'
,"etf:volume_avg_30d":'30天平均交易量'
,"etf:yearly_yield":'年化殖利率'
,"etf:yes":'是'
,"etf:yield":'殖利率'
,"etf:ytd":'年初至今'
,"etf:zacks_category":'資產類型'
,"funds:category":'類別'
,"funds:cot_index":'COT 籌碼指數'
,"funds:formula":'公式:'
,"funds:last_price":'最新價格'
,"funds:net_position":'管理基金淨部位'
,"funds:np_oi":'淨部位 / 未平倉量'
,"funds:position":'部位數'
,"funds:prod_name":'商品名稱'
,"funds:ratio":'管理基金多空比'
,"funds:week_52_max":'相對52週Max值'
,"funds:week_change":'週變動'
,"funds:week_change_ratio":'週變動比例'
,"generic:form:choose":'請選擇...'
,"isaiah:report:addon:select":'報告來源'
,"isaiah:report:empty":'尚無報告'
,"isaiah:report:sector:select":'產業類型'
,"isaiah:report:type:select":'報告類型'
,"knowledge-sharing:tutorial-modal:btn":'我同意遵守使用說明'
,"knowledge_sharing:again_ask":'追問'
,"knowledge_sharing:again_ask:content:error":'追問內容不得為空'
,"knowledge_sharing:again_ask:error":'注意！用戶回覆後才可再次追問'
,"knowledge_sharing:again_ask:ing":'正在追問'
,"knowledge_sharing:again_ask:update:title":'更改追問內容'
,"knowledge_sharing:answer":'回答'
,"knowledge_sharing:answer:again_ask":'提問者追問'
,"knowledge_sharing:answer:best":'此為最佳回答'
,"knowledge_sharing:answer:count":'回答數'
,"knowledge_sharing:answer:disabled":'這則{type}受檢舉，M平方審查後已下架此{type1}。'
,"knowledge_sharing:answer:error":'請輸入回答內容'
,"knowledge_sharing:answer:sort:high:low":'回答數（高到低）'
,"knowledge_sharing:askagain:modal:content":'詳細說明你追問的內容'
,"knowledge_sharing:askagain:modal:title":'追問內容'
,"knowledge_sharing:btn:report":'檢舉'
,"knowledge_sharing:btn:update:againask":'更改追問'
,"knowledge_sharing:category":'分類'
,"knowledge_sharing:column:anonymous":'設定匿名'
,"knowledge_sharing:column:bounty:calculate":'此提問上架費為 <span style="color:#199b7e;font-weight:bold">1 M幣</span>，實際賞金金額為 <span style="color:#199b7e;font-weight:bold">%s M幣</span>'
,"knowledge_sharing:column:bounty:calculate:error":'最低賞金為 2 M幣且不可有小數點'
,"knowledge_sharing:column:bounty:default":'M平方將收取 1 M幣作為上架費'
,"knowledge_sharing:column:bounty:placeholder":'請輸入賞金'
,"knowledge_sharing:column:category:placeholder":'請選擇提問分類'
,"knowledge_sharing:column:desc":'詳細提問說明'
,"knowledge_sharing:column:desc:desc":'說明支援輸入超連結，超連結須為 https:// 完整連結，且後方不能有任何中文字'
,"knowledge_sharing:column:desc:error":'請輸入提問說明'
,"knowledge_sharing:column:desc:placeholder":'詳細說明你的問題，建議指出明確圖表內容、圖文段落，或是已知的人、事、時、物，有助於獲得更完整的回答！'
,"knowledge_sharing:column:pic":'圖片'
,"knowledge_sharing:column:pic:btn":'上傳圖片'
,"knowledge_sharing:column:pic:desc":'最多上傳 2 張圖片，每張大小不超過 5 MB，檔案類型限「JPEG」與「PNG」'
,"knowledge_sharing:column:pic:limit":'已上傳 {total} 張圖片，僅能再上傳 {count} 張'
,"knowledge_sharing:column:pic:limit:count":'圖片限 2 張'
,"knowledge_sharing:column:pic:limit:error":'圖片已達上限，無法上傳新增圖片，你是否要繼續{action}{type}？'
,"knowledge_sharing:column:pic:limit:size":'檔案大小不能超過 5 MB'
,"knowledge_sharing:column:pic:limit:type":'只接受「JPEG」與「PNG」圖片格式'
,"knowledge_sharing:column:title":'標題'
,"knowledge_sharing:column:title:desc":'讓回答者能一眼看懂問題，縮短等待時間、提高答題率！'
,"knowledge_sharing:column:title:placeholder":'一句話描述你的提問'
,"knowledge_sharing:edit":'編輯'
,"knowledge_sharing:edit:question:title":'編輯提問'
,"knowledge_sharing:extend:success":'延長提問成功'
,"knowledge_sharing:has:answer":'有回答'
,"knowledge_sharing:item:go-view":'查看'
,"knowledge_sharing:item:start-answer":'開始回答'
,"knowledge_sharing:mcoin:modal:title":'前往M幣商店'
,"knowledge_sharing:mcoin:sort:high:low":'賞金（高到低）'
,"knowledge_sharing:no:answer":'無回答'
,"knowledge_sharing:placeholder:ans":'開始回答，請輸入至少10個字'
,"knowledge_sharing:publish:againask:success:modal:content":'你的追問已發佈成功'
,"knowledge_sharing:publish:again_ask":'發表追問'
,"knowledge_sharing:publish:again_ask:error":'M幣額度不足<br><br>追問需支付 1 枚M幣，由於你目前持有 0 枚M幣，請前往M幣商店加值後，才能執行追問'
,"knowledge_sharing:publish:answer:error":'你已針對此提問回答，無法再次發表'
,"knowledge_sharing:publish:answer:warning":'提醒！顧及賞金公平性，此回答送出後就無法再次留言及修改內容'
,"knowledge_sharing:publish:bounty_coin:error":'M幣額度不足<br><br>賞金已超過你目前持有的 M幣數量，請前往 M幣商店加值，才可進行提問'
,"knowledge_sharing:publish:coin:error":'M幣額度不足<br><br>發表提問需支付賞金M幣，你目前持有M幣小於 2 枚，加值M幣後便能開始提問'
,"knowledge_sharing:publish:question:btn":'發表提問'
,"knowledge_sharing:publish:success:modal:title":'發表成功'
,"knowledge_sharing:question":'提問'
,"knowledge_sharing:question:anonymous":'匿名用戶'
,"knowledge_sharing:question:answer":'提問回答'
,"knowledge_sharing:question:btn:select":'選為最佳回答'
,"knowledge_sharing:question:category":'提問分類'
,"knowledge_sharing:question:date":'提問日期'
,"knowledge_sharing:question:mcoin":'賞金 {mcoin} M幣'
,"knowledge_sharing:question:select:content":'將此內容選為最佳回答後，回答者將得到賞金 %s M幣，並將關閉回答功能'
,"knowledge_sharing:question:select:success":'選擇成功，賞金已發派給最佳回答者'
,"knowledge_sharing:question:state":'懸賞狀態'
,"knowledge_sharing:question:state:end":'懸賞結束'
,"knowledge_sharing:question:state:ing":'懸賞中'
,"knowledge_sharing:question:state:text1":'懸賞中，賞金 {mcoin} M幣'
,"knowledge_sharing:question:state:text2":'懸賞結束，已分配賞金'
,"knowledge_sharing:question:state:text3":'懸賞結束，等待提問者選擇最佳回答'
,"knowledge_sharing:question:state:text4":'懸賞結束，未選最佳回答'
,"knowledge_sharing:report:reason:empty:error":'請填寫原因'
,"knowledge_sharing:select:all":'全選'
,"knowledge_sharing:select:best":'選最佳回答'
,"knowledge_sharing:title:contain_special_ch":'標題不得包含特殊字元'
,"knowledge_sharing:update:question:btn":'更新提問'
,"knowledge_sharing:update:success":'更新成功'
,"knowledge_sharing:user:achievement:desc":'你的回答與最佳回答總次數'
,"knowledge_sharing:user:achievement:title":'作者成就'
,"knowledge_sharing:user:disabled":'由於你違反MM知識圈相關規定，原因為「{reason}」，目前無權限{type}。'
,"knowledge_sharing:user:fans":'粉絲'
,"knowledge_sharing:user:point:text1":'你已累積第 %s 次未選最佳回答，若達 3 次將停權至下季 1 號，才能發表提問'
,"knowledge_sharing:user:point:text2":'你已累積 3 次以上未選最佳回答，將被停權至下季 1 號，才能發表提問'
,"knowledge_sharing:user:point:text3":'你已累積 3 次以上未選最佳回答，停權至下季 1 號，才能發表提問'
,"knowledge_sharing:view":'瀏覽'
,"login:email:forgot-pass-prompt":'請輸入帳號 Email 並送出，系統將寄送密碼重置通知信給您。<br><br>若之前採用 Facebook / Google / 微信等方式登入，請直接點擊上方社群帳號登入按鈕。'
,"login:msg:change-email-ok":'已成功更新 Email 信箱'
,"login:msg:email-in-use2":'此帳號已是 財經M平方 會員，請使用 {type} 登入'
,"login:msg:invalid-user-or-pass":'無效的帳號或密碼'
,"login:msg:passwd-length":'密碼至少需要%s碼'
,"login:msg:pls-login":'請先登入會員。'
,"macro-cycle-growth":'擴張'
,"macro-cycle-recession":'衰退'
,"macro-cycle-recovery":'復甦'
,"macro-cycle-slow_growth":'趨緩'
,"mcoin:agreement:title":'<div style=\'padding-top: 1em\'><label><input type=\'checkbox\' name=\'confirm\'> 我同意財經M平方之<a href=\'/terms\' target=\'_blank\'>M幣使用協議</a></label></div>'
,"mcoin:agreement:unchecked":'請先同意使用協議'
,"mcoin:code:empty":'請輸入折扣碼 / 兌換碼'
,"mcoin:code:enter":'若有課程折扣碼，請在此輸入:'
,"mcoin:code:redeem_ok":'兌換成功'
,"mcoin:code:unused":'你已輸入課程折扣碼，請按「套用折扣碼」完成折抵'
,"mcoin:discount:amount":'(已折抵 {discount_amount} M幣)'
,"mcoin:discount:pass":'已成功折抵 {own} M幣！數量有限，請盡速兌換。'
,"mcoin:discount:redeem":'兌換課程'
,"mcoin:exchange-max:success":'兌換成功！本期可享有 MM Max 至 {nextPayDate}。'
,"mcoin:exchange-prime:success":'兌換成功！本期可享有 MM Prime 至 {nextPayDate}。'
,"mcoin:exchange-pro:success":'兌換成功！本期可享有 MM PRO 至 {nextPayDate}。'
,"mcoin:exchange-video:success":'期待與您一起學習！'
,"mcoin:process:refund":'M幣退費確認'
,"mcoin:process:tip":'M幣使用確認'
,"mcoin:redeem:sure":'套用折扣碼'
,"mcoin:user:knowledge_sharing":'你目前有 {own} M幣，是否要使用 <span id="final-amount">{amount}</span> M幣{name}?'
,"mcoin:user:owned":'您目前有 {own} M幣，是否要使用 <span id=\'final-amount\'>{amount}</span> M幣兌換：<br />{name} ?'
,"mcoin:user:owned:refund":'您目前有 {own} M幣，是否要申請退費 <span id=\'final-amount\'>{amount}</span> M幣?'
,"mcoin:use_discount:btn":'使用課程折扣碼'
,"mm-ai:ask":'AI 問答'
,"mm-ai:ask:hint":'輸入關鍵字或問題，例如「為何美國 CPI 上升？」、「中國經濟看法」，我會用 M平方報告與數據為你解答。'
,"mm-ai:ask:placeholder":'詢問 AI 財經與網站使用問題'
,"mm-ai:ask:title":'MM AI 問答'
,"mm-ai:copy:disclaimers":'文字內容由 [財經M平方](https://www.macromicro.me/) MM AI 服務產出'
,"mm-ai:disclaimer":'AI 提供的數據與資訊僅供參考，所呈現的內容不應被視為任何形式的投資建議、專業意見或行動建議。使用者應自行評估並負責其所做的任何決策。'
,"mm-ai:error":'系統問題，暫時無法回應你的問題。你可以再次提問，或嘗試其他內容。'
,"mm-ai:feedback:empty":'請輸入您的回饋'
,"mm-ai:feedback:thank":'感謝您的回饋'
,"mm-ai:loading:1":'嘗試理解問題'
,"mm-ai:loading:2":'正在搜尋 M平方資料庫'
,"mm-ai:loading:3":'從 M平方資料庫提取相關內容中'
,"mm-ai:loading:4":'轉化與提煉內容精華'
,"mm-ai:loading:5":'準備回覆問題'
,"mm-ai:search":'站內搜尋'
,"mm-ai:search:hint":'輸入關鍵字，例如「美國 CPI」、「景氣循環」，我會幫你找到相關文章與圖表。'
,"mm-ai:search:placeholder":'搜尋關鍵字，查找文章、圖表'
,"mm-ai:switch":'切換至'
,"mm:sentiment:last_week":'上週值'
,"mm:sentiment:login":'請登入以進行投票'
,"mm:sentiment:login_first":'請登入後投票分享你的看法，即可查看完整趨勢。'
,"mm:sentiment:neutral":'中立'
,"mm:sentiment:newest":'最新'
,"mm:sentiment:optimism":'樂觀'
,"mm:sentiment:pessimistic":'悲觀'
,"mm:sentiment:trend":'完整趨勢'
,"mm:sentiment:vote_first":'請先投票分享你的看法，即可查看完整趨勢。'
,"mmgpt:answer_copied":'已複製！'
,"mmgpt:calculating":'OpenAI 運算中...'
,"mmgpt:confirm_delete":'刪除後將不會顯示此詢問結果，確定刪除嗎？'
,"mmgpt:copy":'複製'
,"mmgpt:desc":'本服務為財經Ｍ平方應用 OpenAI ChatGPT 4.1 技術的總經 AI 工具。您可以在下方文字框輸入問題描述，MacroMicroGPT 即能針對問題給予專屬文字與動態圖表回覆。不知道如何使用嗎？點擊「<a class=\'show-tutorial mm-primary\'  target=\'_blank\' href=\'/\'>使用教學</a>」來增加您對經濟趨勢掌握度吧！'
,"mmgpt:fill_feedabck":'請撰寫說明文字...'
,"mmgpt:following_charts":'以下為相關圖表:'
,"mmgpt:generating":'內容生成中...'
,"mmgpt:got_feedback":'謝謝您的反饋！'
,"mmgpt:helpful":'有幫助'
,"mmgpt:hint:login":'若您已經是會員請<a href=\'/login?next=%2Fmm-gpt\'>點此登入</a>。'
,"mmgpt:hint:normal":'您這個月還有 {x} 次使用額度，若為訂閱會員，每月可享有 5 次使用額度，<a href=\'/subscribe\' target=\'_blank\' class=\'mm-primary click-subscribe\'>點我立刻成為訂閱會員</a>'
,"mmgpt:hint:no_pro":'此服務僅限財經Ｍ平方訂閱專屬，每月可享有 5 次使用額度，可利用 AI 幫助投資決策養成，<a class=\'mm-primary click-subscribe\' href=\'/subscribe\'>點我立刻成為訂閱會員</a>'
,"mmgpt:hint:pro":'訂閱會員專屬 AI 服務，您這個月還有 {x} 次使用額度，系統將在每月 1 號重新配送 5 次使用權利'
,"mmgpt:in_maintain":'本頁功能優化更新中，感謝耐心等待'
,"mmgpt:is_generating":'目前 GPT 內容生成中，請於該回覆完成後再查閱詢問紀錄。'
,"mmgpt:make_better":'讓我們提供更棒的 AI 工具'
,"mmgpt:make_better_content":'感謝您對 MacroMicroGPT 提出看法，請在下方簡述您的建議，您的反饋將讓財經M平方的功能變得更好。'
,"mmgpt:max_saved":'僅保存近期詢問的 20 個問題'
,"mmgpt:no_quota:normal":'您本月的使用額度已用完，若為訂閱會員，每月可享有 5 次使用額度，可利用 AI 幫助投資決策養成，<a href=\'/subscribe\' target=\'_blank\' class=\'mm-primary\'>點我立刻成為訂閱會員</a>'
,"mmgpt:only_do_one":'一個財經M平方帳號在同時間僅能提交一個問題，請確認是否有其他裝置/分頁生成內容中。'
,"mmgpt:only_reference":'AI 生成的內容僅供參考，並非任何投資建議'
,"mmgpt:please_ask":'請輸入您想了解的總經問題'
,"mmgpt:query_empty":'目前尚未詢問'
,"mmgpt:query_history":'近期詢問紀錄'
,"mmgpt:question_empty":'請輸入問題'
,"mmgpt:quota_empty":'您本月的使用額度已用完，系統將在每月 1 號重新配送 5 次使用權利，屆時您能重新嘗試發問'
,"mmgpt:related_charts":'相關推薦圖表'
,"mmgpt:sent_time":'於 {time} 詢問'
,"mmgpt:unhelpful":'沒幫助'
,"mmgpt:view_chart":'查看圖表'
,"mmgpt:welcome":'嗨，我是 MacroMicroGPT，您的總經學習好夥伴，為了幫助學習效果，建議提問與總經相關的問題，您可以試試下列問題示範：'
,"monthly:btn:login-as-pro":'<div class=\'bg-dark text-light text-center py-2 mb-3\' style=\'margin-top:-1.5rem\'>已經是 MM PRO 了嗎? <a href=\'/login?next=/mails/monthly_report\' class=\'mm-primary\'>登入PRO閱讀報告</a></div>'
,"monthly:btn:login-as-subscriber":'<div class=\'bg-dark text-light text-center py-2 mb-3\' style=\'margin-top:-1.5rem\'>已經是訂閱會員了嗎? <a href=\'/login?next=/mails/monthly_report\' class=\'mm-primary\'>登入閱讀報告</a></div>'
,"nav2:blog":'部落格'
,"nav2:commodities":'原物料觀測站'
,"nav2:data-commodities":'原物料專區'
,"nav2:discuss":'關鍵圖表'
,"nav2:isaiah:report":'獨家產業報告'
,"nav2:more":'更多'
,"nav2:time-line":'時間軸'
,"nav2:us-financial-report-database":'美股財報資料庫'
,"nav:blog":'部落格'
,"nav:commodities":'原物料觀測站'
,"nav:data-commodities":'原物料專區'
,"nav:discuss":'關鍵圖表'
,"nav:time-line":'時間軸'
,"payment:label:company-name":'抬頭'
,"payment:label:device-cert":'自然人憑證條碼'
,"payment:label:device-cert:placeholder":'共16碼'
,"payment:label:device-email":'交易通知 Email'
,"payment:label:device-email:placeholder":'請填可正常收信的電子信箱'
,"payment:label:device-mobile":'手機載具條碼'
,"payment:label:device-mobile:placeholder":'手機條碼為 / 開頭，共8碼'
,"payment:label:inv-device":'選擇發票載具'
,"payment:label:inv-device-1":'藍新金流平台載具'
,"payment:label:inv-device-2":'手機載具'
,"payment:label:inv-device-3":'自然人憑證'
,"payment:label:inv-type-1":'二聯式捐贈發票-財團法人創世福利基金會'
,"payment:label:inv-type-2":'二聯式電子發票'
,"payment:label:inv-type-3":'三聯式需打統編'
,"payment:label:quick-pay":'快速結帳'
,"payment:label:quick-pay:more":'(使用存檔之信用卡支付，後四碼：%s)'
,"payment:label:ubn":'統一編號'
,"payment:label:update-my-inv-settings":'同步更新我的發票設定'
,"payment:label:whats-this":'這是什麼?'
,"payment:text:explain-inv-devices":'載具是指電子發票儲存的地方，如您沒有慣用的手機或自然人憑證載具來儲存發票的話，建議您可以直接選擇藍新金流平台載具。若本次發票中獎了，藍新金流平台與財經M平方便會通知您後續兌獎事宜。'
,"payment:title:inv-type":'發票形式'
,"paynow:dialog:btn:apply":'套用折扣碼'
,"paynow:dialog:help:no-multi-codes":'折扣優惠恕不能合併使用'
,"paynow:dialog:label:amount":'金額：'
,"paynow:dialog:label:item":'項目：'
,"paynow:dialog:title":'信用卡付款'
,"poll:btn:vote":'投票'
,"poll:meta:close-time":'截止'
,"popup:btn:cancel":'下次再說'
,"pro:btn:diy":'製圖'
,"pro:btn:edit":'編輯'
,"pro:msg:invalid-plan":'請選擇方案'
,"pro:msg:tos-agree-prompt":'是否已閱讀並同意 <a href=\'/terms\' target=\'_blank\'>M平方服務條款、隱私權政策與免責聲明</a>?'
,"raw:agriculture":'農作物'
,"raw:all_products":'全商品'
,"raw:commodity":'商品'
,"raw:consume_ranking":'消費排名'
,"raw:consume_ratio":'消費佔比'
,"raw:demand":'需求'
,"raw:etf_not_found":'尚無相關 ETF，更多標的可至 ETF 專區查詢'
,"raw:exports":'出口'
,"raw:global_demand_ratio":'原物料需求全球佔比'
,"raw:global_prod_ratio":'原物料產量全球佔比'
,"raw:imports":'進口'
,"raw:not_full_released":'（數據尚未完整公布）'
,"raw:prod_ranking":'生產排名'
,"raw:prod_ratio":'生產佔比'
,"raw:ratio_too_small":'若比例呈現 0% 表示數值小於 0.1%'
,"raw:sector":'板塊'
,"raw:supply":'供給'
,"raw:top10:abs:demand":'最新消費絕對值 Top 10'
,"raw:top10:abs:export":'最新出口絕對值 Top 10'
,"raw:top10:abs:import":'最新進口絕對值 Top 10'
,"raw:top10:abs:reserve":'最新儲量絕對值 Top 10'
,"raw:top10:abs:supply":'最新產量絕對值 Top 10'
,"raw:top10:ratio:demand":'最新消費佔比 Top 10'
,"raw:top10:ratio:export":'最新出口佔比 Top 10'
,"raw:top10:ratio:import":'最新進口佔比 Top 10'
,"raw:top10:ratio:reserve":'最新儲量佔比 Top 10'
,"raw:top10:ratio:supply":'最新產量佔比 Top 10'
,"raw:top5:change:demand":'歷史消費變化 Top 5'
,"raw:top5:change:export":'歷史出口變化 Top 5'
,"raw:top5:change:import":'歷史進口變化 Top 5'
,"raw:top5:change:ratio:demand":'歷史消費佔比變化 Top 5'
,"raw:top5:change:ratio:export":'歷史出口佔比變化 Top5'
,"raw:top5:change:ratio:import":'歷史進口佔比變化 Top 5'
,"raw:top5:change:ratio:supply":'歷史產量佔比變化 Top 5'
,"raw:top5:change:supply":'歷史產量變化 Top 5'
,"raw:unit:b_barrels":'十億桶'
,"raw:unit:b_cubic_feet_day":'十億立方英尺/日'
,"raw:unit:exajoules":'艾焦耳'
,"raw:unit:k_barrels_day":'千桶/日'
,"raw:unit:k_tonnes":'千公噸'
,"raw:unit:k_usd":'1,000 美元'
,"raw:unit:metric_ton":'公噸'
,"raw:unit:m_bags":'百萬袋(60公斤)'
,"raw:unit:m_bales":'百萬包(480磅)'
,"raw:unit:m_tonnes":'百萬公噸'
,"raw:unit:t_cubic_m":'兆立方米'
,"ready_share:btn:chart":'發表圖表'
,"ready_share:field:desc:min_chars":'【說明】請輸入至少 %s 個字'
,"resource:title:metal":'金屬'
,"search:title":'搜尋'
,"season_chart:data:mode":'數據呈現方式'
,"season_chart:mode:ratio":'與年初比值'
,"season_chart:mode:raw":'原始值'
,"sector2:chart-permissions":'圖表分類'
,"sector2:country:global":'未上市'
,"sector2:data-source":'數據來源'
,"sector2:orderbybook":'依收藏數（高到低）'
,"sector2:orderbymm":'MM研究員排序'
,"sector2:orderbyview":'依瀏覽數（高到低）'
,"sector2:select:all":'全部'
,"sector2:tw:etf":'台灣 ETF'
,"sector2:us:etf":'美國 ETF'
,"sectors:automobile:element":'該產業主要成分股名單：和泰車、裕隆、三陽工業、汎德永業、中華、裕日車、東陽、堤維西、帝寶、麗清'
,"sectors:block":'您好，<br><br>目前「產業決策平台」權限贈送活動已結束。未來，我們將結合全新開發的美股財報資料庫，再度開放上線，敬請期待！'
,"sectors:block:btn:login":'前往登入'
,"sectors:block:not:login":'您好，<br><br>目前「產業決策平台」權限贈送活動已結束。未來，我們將結合全新開發的美股財報資料庫，再度開放上線，敬請期待！<br><br>若您已具備使用權限，歡迎登入該帳號前往瀏覽。'
,"sectors:bm:element":'該產業主要成分股名單：美時、葡萄王、中化、佳醫、永信、晶碩、生達、台耀、承業醫、杏輝'
,"sectors:bmc:element":'該產業主要成分股名單：興富發、欣陸、潤隆、潤弘、國產、中工、冠德、遠雄、根基、達欣工'
,"sectors:cement:element":'該產業主要成分股名單：台泥、亞泥、嘉泥、環泥、幸福、信大、東泥'
,"sectors:chart:date":'截至'
,"sectors:chemicals:element":'該產業主要成分股名單：長興、中纖、東聯、南寶、和桐、興農、台肥、勝一、和益、永記'
,"sectors:ci:element":'該產業主要成分股名單：中華電、台灣大、啟碁、遠傳、智邦、中磊、智易、合勤控、美津、神腦'
,"sectors:company:top:title":'代表廠商'
,"sectors:cpe:element":'該產業主要成分股名單：和碩、廣達、仁寶、緯創、英業達、華碩、緯穎、宏碁、佳世達、微星'
,"sectors:desc:global":'本專區的每個分頁以單一產業為主題，呈現該產業的全球數據，讓您以深且廣的全視角掌握產業動態。透過專區，產業的上中下游關係鏈、重點公司的市佔、財報數字皆一目了然，讓您的投資決策及商情判斷更簡單！'
,"sectors:desc:index":'本圖表可用來觀察 27 個產業在固定時間內的指數走勢和表現，除此之外，還可依照使用需求，客製化調整時間區間，包括 1 週、1 個月、年初至今到 5 年區段供選擇。'
,"sectors:desc:revenue":'本圖表可用來觀察 27 個產業最新月份的營收動能，包括年增率和月增率。'
,"sectors:ec:element":'該產業主要成分股名單：華新、大亞、聲寶、華榮、禾聯碩、燦星網、三洋電、宏泰、大山、合機'
,"sectors:ed:element":'該產業主要成分股名單：大聯大、文曄、聯強、至上、益登、威健、華立、全科、崇越、增你強'
,"sectors:em:element":'該產業主要成分股名單：東元、大同、士電、上銀、中興電、勤美、瑞智、華城、中宇、亞力'
,"sectors:epc:element":'該產業主要成分股名單：台達電、國巨、欣興、群光、正崴、致伸、華通、健鼎、南電、瀚宇博'
,"sectors:etf:1m":'1月績效%'
,"sectors:etf:1y":'1年績效%'
,"sectors:etf:3m":'3月績效%'
,"sectors:etf:change":'漲跌%'
,"sectors:etf:ytd":'年初至今績效%'
,"sectors:fi:element":'該產業主要成分股名單：國泰金、富邦金、中信金、三商壽、元大金、兆豐金、台新金、第一金、玉山金、合庫金'
,"sectors:food:element":'該產業主要成分股名單：統一、大成、卜蜂、佳格、大統益、南僑、味全、福壽、福懋油、聯華'
,"sectors:form:organization":'公司名稱'
,"sectors:form:success":'已成功送出，我們將盡速回覆您。'
,"sectors:gc:element":'該產業主要成分股名單：台玻、冠軍、中釉、和成、凱撒衛'
,"sectors:global:company:amat":'AMAT（應用材料）'
,"sectors:global:company:amd":'AMD（超微）'
,"sectors:global:company:arm":'ARM（安謀）'
,"sectors:global:company:asml":'ASML（艾司摩爾）'
,"sectors:global:company:auo":'AUO（友達）'
,"sectors:global:company:automotive":'車用'
,"sectors:global:company:boe":'Boe Technology Group（京東方）'
,"sectors:global:company:broadcom":'Broadcom（博通）'
,"sectors:global:company:cadence":'Cadence（益華電腦）'
,"sectors:global:company:chot":'CHOT（彩虹光電）'
,"sectors:global:company:cn":'中國'
,"sectors:global:company:computing":'運算及數據儲存'
,"sectors:global:company:consumer":'消費性'
,"sectors:global:company:eu":'歐洲'
,"sectors:global:company:gfs":'GFS（格羅方德）'
,"sectors:global:company:hannstar":'Hannstar（瀚宇彩晶）'
,"sectors:global:company:hkc":'HKC（惠科）'
,"sectors:global:company:industrial":'工業'
,"sectors:global:company:infovision":'infovision（龍騰光電）'
,"sectors:global:company:innolux":'Innolux（群創）'
,"sectors:global:company:intel":'Intel（英特爾）'
,"sectors:global:company:jp":'日本'
,"sectors:global:company:lg":'LG Display（樂金）'
,"sectors:global:company:marvell":'Marvell（邁威爾）'
,"sectors:global:company:mediatek":'Mediatek（聯發科）'
,"sectors:global:company:micron":'Micron（美光）'
,"sectors:global:company:nvidia":'Nvidia（輝達）'
,"sectors:global:company:qualcomm":'Qualcomm（高通）'
,"sectors:global:company:samsung":'Samsung（三星）'
,"sectors:global:company:sharp":'Sharp（夏普）'
,"sectors:global:company:shin-etsu":'Shin-Etsu（信越化學）'
,"sectors:global:company:sumco":'Sumco（勝高）'
,"sectors:global:company:synopsys":'Synopsys（新思科技）'
,"sectors:global:company:tcl":'TCL（華星光電）'
,"sectors:global:company:tianma":'TIANMA（天馬微電子）'
,"sectors:global:company:tsmc":'TSMC（台積電）'
,"sectors:global:company:umc":'UMC（聯電）'
,"sectors:global:company:us":'美國'
,"sectors:global:company:wired":'有線通訊'
,"sectors:global:company:wireless":'無線通訊'
,"sectors:global:desc:downstreamF":'我們精選產業中知名度、市佔率較高的五家半導體產業下游廠商，他們的出貨和營運狀況，能有效反映目前半導體產業需求和動態'
,"sectors:global:desc:finance":'我們精選產業中知名度、市佔率較高的五家關鍵廠商，他們的出貨和營運狀況，能有效反映目前面板產業需求和動態'
,"sectors:global:desc:industry":'全球面板產業的主要廠商的市佔率以及不同產品別的市佔率分布'
,"sectors:global:desc:midstreamF":'我們精選產業中知名度、市佔率較高的五家半導體產業中游廠商，他們的出貨和營運狀況，能有效反映目前半導體產業需求和動態'
,"sectors:global:desc:semiconductor:industry":'半導體產業的主要上中下游廠商的市佔率以及不同產品別的市佔率分布'
,"sectors:global:desc:semiconductor:top":'本圖表可觀察不同時間內，全球五個主要面板廠商股價報酬率表現'
,"sectors:global:desc:upstreamF":'我們精選產業中知名度、市佔率較高的五家半導體產業上游廠商，他們的出貨和營運狀況，能有效反映目前半導體產業需求和動態'
,"sectors:global:eps:unit:krw":'韓圜'
,"sectors:global:eps:unit:nt":'台幣'
,"sectors:global:eps:unit:rmb":'人民幣'
,"sectors:global:eps:unit:usd":'美元'
,"sectors:global:finance:chart2":'大尺寸顯示面板出貨量'
,"sectors:global:finance:panel:company":'千片'
,"sectors:global:finance:panel:product":'千片'
,"sectors:global:finance:semiconductor:ratio":'百萬美元'
,"sectors:global:finance:semiconductor:revenue":'百萬美元'
,"sectors:global:finance:thousand":'千片'
,"sectors:global:finance:unit:day":'單位：天'
,"sectors:global:finance:unit:percent":'單位：%'
,"sectors:global:finance:unit:thousand":'單位：千片'
,"sectors:global:finance:unit:usd":'單位：百萬(美元)'
,"sectors:global:industry:chart:company":'產業市佔率(依廠商分)'
,"sectors:global:industry:chart:days":'庫存天數'
,"sectors:global:industry:chart:panel:company":'產業市佔率(依廠商分)'
,"sectors:global:industry:chart:panel:days":'庫存天數'
,"sectors:global:industry:chart:panel:product":'產業市佔率(依種類分)'
,"sectors:global:industry:chart:panel:shipment":'出貨量'
,"sectors:global:industry:chart:product":'產業市佔率(依種類分)'
,"sectors:global:industry:chart:semiconductor:downstream":'下游庫存天數'
,"sectors:global:industry:chart:semiconductor:midstream":'中游庫存天數'
,"sectors:global:industry:chart:semiconductor:ratio":'半導體設備出貨(依國家分)'
,"sectors:global:industry:chart:semiconductor:revenue":'半導體營收(依市場分)'
,"sectors:global:industry:chart:semiconductor:upstream":'上游庫存天數'
,"sectors:global:industry:chart:shipment":'出貨量'
,"sectors:global:panel:overview:backlight":'日亞化學、LG Innotek、晶元光電'
,"sectors:global:panel:overview:chemicals":'信越化學、JSR、東京大賀工業、杜邦'
,"sectors:global:panel:overview:display-module":'三星電子、LG Display、京東方、群創、友達'
,"sectors:global:panel:overview:mask":'大日本光罩、台灣光罩、日本豪雅'
,"sectors:global:panel:overview:monitor-display":'三星、LG Display'
,"sectors:global:panel:overview:panel":'三星電子、LG Display、京東方、群創、友達'
,"sectors:global:panel:overview:pc-nb":'聯想、HP、戴爾'
,"sectors:global:panel:overview:tv":'三星、LG Display、Sony'
,"sectors:global:semiconductor:overview:brand":'輝達、超微、英特爾、美光、三星電子'
,"sectors:global:semiconductor:overview:eda":'益華電腦、新思科技、明導國際'
,"sectors:global:semiconductor:overview:equipment":'艾司摩爾、應用材料、科林研發、東京威力科創、科磊'
,"sectors:global:semiconductor:overview:foundry":'台積電、三星電子、格羅方德、聯電、中芯國際'
,"sectors:global:semiconductor:overview:ic":'聯發科、高通、博通、邁威爾、瑞昱、聯詠'
,"sectors:global:semiconductor:overview:ip":'安謀、新思科技、益華電腦、進想科技、艾爾波'
,"sectors:global:semiconductor:overview:material":'信越化學、杜邦、英特格、巴斯夫'
,"sectors:global:semiconductor:overview:pt":'日月光投控、艾克爾、矽品、力成'
,"sectors:global:semiconductor:overview:silicon":'信越化學、勝高、環球晶'
,"sectors:global:semiconductor:title:downstreamF":'下游財務報表'
,"sectors:global:semiconductor:title:midstreamF":'中游財務報表'
,"sectors:global:semiconductor:title:upstreamF":'上游財務報表'
,"sectors:global:top:desc":'本圖表可觀察不同時間內，全球五個主要面板廠商股價報酬率表現'
,"sectors:global:unit:eu":'百萬,歐元'
,"sectors:global:unit:jp":'百萬,日圓'
,"sectors:global:unit:ko":'百萬,韓圜'
,"sectors:global:unit:nt":'千元,台幣'
,"sectors:global:unit:rmb":'百萬,人民幣'
,"sectors:global:unit:usd":'百萬,美元'
,"sectors:irons:element":'該產業主要成分股名單：中鋼、大成鋼、燁輝、東和鋼鐵、中鴻、豐興、春源、中鋼構、允強、新光鋼'
,"sectors:is:element":'該產業主要成分股名單：精誠、零壹、邁達特、敦陽科、凌群、三商電、華經、關貿、訊連、傳奇'
,"sectors:oge:element":'該產業主要成分股名單：台塑化、全國、山隆、台汽電、大台北、新海、欣天然、欣高'
,"sectors:optoelectronics:element":'該產業主要成分股名單：友達、群創、台表科、瑞儀、大立光、富采、億光、明基材、達運、亞光'
,"sectors:other:element":'該產業主要成分股名單：鴻海、金寶、鴻準、漢唐、帆宣、亞翔、可成、旭隼、致茂、洋基工程'
,"sectors:plastic:element":'該產業主要成分股名單：台化、南亞、台塑、聯成、台聚、中石化、國喬、台達化、華夏、炎洲'
,"sectors:pp:element":'該產業主要成分股名單：永豐餘、榮成、正隆、華紙、寶隆、士紙、永豐實'
,"sectors:rubber:element":'該產業主要成分股名單：正新、建大、台橡、國際中橡、南帝、南港、華豐、鑫永銓、厚生、申豐'
,"sectors:segment:Backlights":'背光源'
,"sectors:segment:Chemicals":'化學品'
,"sectors:segment:Monitors/Displays":'監視器/顯示器'
,"sectors:segment:Panels":'面板'
,"sectors:segment:PC/NB":'PC/NB'
,"sectors:segment:Photomasks":'光罩'
,"sectors:segment:TV":'電視'
,"sectors:semiconductor:element":'該產業主要成分股名單：台積電、日月光投控、聯發科、聯電、聯詠、瑞昱、華邦電、力成、力積電、新唐'
,"sectors:spotlight:index:unit":'近 1 個月漲跌幅'
,"sectors:spotlight:revenue-YoY:unit":'%s 月年增率'
,"sectors:textile:element":'該產業主要成分股名單：遠東新、新纖、聚陽、力鵬、儒鴻、福懋、南紡、廣越、如興、得力'
,"sectors:title:global":'全球產業專區'
,"sectors:tmr:element":'該產業主要成分股名單：統一超、三商、特力、遠百、三商家購、高林、益航、麗嬰房、潤泰全、阿瘦'
,"sectors:tourism:element":'該產業主要成分股名單：王品、雄獅、八方雲集、晶華、寒舍、好樂迪、雲品、鳳凰、六福、華園'
,"sectors:transport:element":'該產業主要成分股名單：長榮、長榮航、華航、陽明、萬海、台灣高鐵、漢翔、台船、榮運、長榮航太'
,"series:api:msg:confirm-submit":'已選取 {cnt} 筆數據，確定要送出數據需求申請?'
,"series:dl:hint:left":'本月下載額度目前已使用 {used} 筆（每月共 {total} 筆），目前僅能下載 {left} 筆數據'
,"series:dl:hint:used2":'下載額度目前已使用 <span class="text-primary">{used}</span> 筆（每月共 {total} 筆）'
,"series:dl:title":'數據下載紀錄'
,"series:dl:used_up":'您本月的下載額度已用完，系統將在每月 1 號重新配送 %s 筆下載額度，屆時您能重新下載'
,"shared_chart:user:official_name":'財經M平方'
,"stats:spec:units":'單位'
,"thirteenf:y_axis":'持倉比例'
,"time-line:tab:event":'事件'
,"toggle:watermark":'浮水印'
,"toolbox:back-test:mom":'月'
,"toolbox:back-test:qoq":'季'
,"toolbox:back-test:remove":'是否要刪除此回測圖表?'
,"toolbox:back-test:result-desc":'{\"return_of_investment\":{\"def\":\"總報酬率：(期末權益-期初權益)/期初權益。\",\"name\":\"總報酬率\",\"unit\":\"percentage\"},\"annualized_returns\":{\"def\":\"年化報酬率：使用總報酬率反推得之。<br />總報酬率(%) = (1+年化報酬率)^(年數)。\",\"name\":\"年化報酬率\",\"unit\":\"percentage\"},\"trading_times\":{\"def\":\"交易次數：每次買進及賣出的交易次數加總 (買進及賣出各算一次)。\",\"name\":\"交易次數\",\"unit\":\"int\"},\"win_rate\":{\"def\":\"獲勝機率：總獲利次數 / 平倉交易次數 (一買一賣計算一次)。\",\"name\":\"勝率\",\"unit\":\"percentage\"},\"payoff_ratio\":{\"def\":\"盈虧比：每次交易平均獲利/每次交易平均虧損。\",\"name\":\"盈虧比\",\"unit\":\"ratio\"},\"profit_dropdown\":{\"def\":\"獲利風險比：淨利 / 最大回檔數值 (過去回測期間，整體淨利除以最大連續回檔金額)。\",\"name\":\"獲利風險比\",\"unit\":\"ratio\"},\"profit_factor\":{\"def\":\"獲利因子：每次交易之總獲利金額 / 總虧損金額。\",\"name\":\"獲利因子\",\"unit\":\"ratio\"},\"max_dropdown\":{\"def\":\"最大回檔幅度：(最小權益值-最大權益值)/最大權益值。\",\"name\":\"最大回檔幅度\",\"unit\":\"percentage\"},\"yearly_volatility\":{\"def\":\"年化波動率：年報酬率的標準差(波動程度)。\",\"name\":\"年化波動率\",\"unit\":\"percentage\"},\"kelly\":{\"def\":\"凱利公式(Kelly formula)：獲勝機率 - (虧損機率 / 賠率)，其中賠率=報酬率/虧損率。此為參考的最佳投資金額比率，例如：計算結果為23%，則100萬本金建議最高投資23萬。\",\"name\":\"凱利公式\",\"unit\":\"percentage\"},\"sharp_ratio\":{\"def\":\"夏普比率(Sharp ratio)：(報酬率 – 無風險利率) / 標準差。計算結果可作為評估投組「在承受1%的風險下，能得到多少報酬？」的參考，衡量投資組合績效與穩定性。\",\"name\":\"夏普公式\",\"unit\":\"float\"},\"value_at_risk\":{\"def\":\"在0.05的信賴水準下，策略在未來特定時期內的最大可能損失比例。\",\"name\":\"風險價值模型\",\"unit\":\"percentage\"}}'
,"toolbox:back-test:result-error":'計算錯誤'
,"toolbox:back-test:result-error:need-strategy":'進場策略及出場策略至少一項'
,"toolbox:back-test:save-error":'儲存錯誤'
,"toolbox:back-test:save:fail":'儲存前請先計算'
,"toolbox:back-test:save:success":'儲存成功！可至「<a href=\"/user/dashboards\" target=\"_blank\">我的儀表板</a>」>「回測」查看。'
,"toolbox:back-test:shift:integer":'數據移動期數請輸入正負整數'
,"toolbox:back-test:strategy:buy":'做多'
,"toolbox:back-test:strategy:cumulative_return_threshold":'[\"當\",\"增\"]'
,"toolbox:back-test:strategy:less-than":'小於'
,"toolbox:back-test:strategy:ma:error":'均線分析期數須介於1~255'
,"toolbox:back-test:strategy:ma_crossover_ma":'[\"當\",\"期均線\"]'
,"toolbox:back-test:strategy:ma_crossover_price":'[\"當數值\",\"期均線\"]'
,"toolbox:back-test:strategy:more-than":'大於'
,"toolbox:back-test:strategy:movings-desc":'數據移動期數單位同指標資料頻率，正值代表向後移動，負值代表向前移動。'
,"toolbox:back-test:strategy:num-change":'數值變動'
,"toolbox:back-test:strategy:period:error":'數據期別必須介於1~255'
,"toolbox:back-test:strategy:sell":'做空'
,"toolbox:back-test:strategy:tech-analysis":'均線分析'
,"toolbox:back-test:trading_signals":'訊號設定'
,"toolbox:back-test:yoy":'年'
,"toolbox:backtest:above":'大於'
,"toolbox:backtest:below":'小於'
,"toolbox:backtest:buy_date":'買進日期'
,"toolbox:backtest:continuously":'連續'
,"toolbox:backtest:continuous_growth":'連續{n}期{sign}'
,"toolbox:backtest:cumulative_return_threshold":'當{n}增{sign}{threshold}'
,"toolbox:backtest:decline":'向下'
,"toolbox:backtest:ma_crossover_ma":'當{ma_1}期均線{sign}{ma_2}期均線'
,"toolbox:backtest:ma_crossover_price":'當數值{sign}{ma}期均線'
,"toolbox:backtest:period":'期'
,"toolbox:backtest:profit":'盈虧'
,"toolbox:backtest:rise":'向上'
,"toolbox:backtest:sold_date":'賣出日期'
,"toolbox:backtest:three_strategies":'策略最多只能設定3項'
,"toolbox:backtest:trade_at_threshold":'連續{n}期{sign}{threshold}'
,"toolbox:backtest:trading_signals":'訊號設定'
,"toolbox:bar:freq_tip":'數據項目需統一頻率才能進行運算，請先選擇好您想比較的頻率'
,"toolbox:chart:addon_alert":'您好<br/><br/>此圖表包含 {planTexts} 專屬之產業 / 美股數據。您目前尚未擁有使用權限，系統已自動移除該筆數據資料。<br/><br/>如需完整使用產業數據，歡迎 <a href=\'/subscribe\'>升級方案</a> 解鎖！'
,"toolbox:correlation:and":'與'
,"toolbox:correlation:error":'計算錯誤，請確認參數或聯絡管理員'
,"toolbox:correlation:error:must-have-two-stat":'必須選擇兩個數據'
,"toolbox:correlation:error:same-stat":'請選擇不同數據'
,"toolbox:correlation:result:behind":'{stat1} 落後 {stat2} {period} {freq}'
,"toolbox:correlation:result:daily":'天'
,"toolbox:correlation:result:lead":'{stat1} 領先 {stat2} {period} {freq}'
,"toolbox:correlation:result:monthly":'月'
,"toolbox:correlation:result:quarterly":'季'
,"toolbox:correlation:result:weekly":'週'
,"toolbox:correlation:result:yearly":'年'
,"toolbox:frequency:limit":'所選頻率不得低於原始數據頻率'
,"toolbox:next-step":'下一步'
,"toolbox:opn_m:hint":'非0常數'
,"toolbox:quote-change":'漲跌幅'
,"toolbox:return":'報酬率'
,"toolbox:season-chart":'季節性'
,"toolbox:season-chart:aggn_desc":'將數據從高頻率轉為低頻率的整合方式。<br>以日頻率轉為周頻率為例:<br>平均:將該周所有日數據平均<br>加總:將該周所有日數據加總<br>最後:只取該周內最後日數據的值'
,"toolbox:season-chart:ytype_desc":'Y軸以對數刻度呈現，較容易觀察數據比例，而非絕對值的變化<br>（若數據有負值，對數刻度將無法顯示）'
,"upgrade-prime:invalid-payment-methods":'因您目前採用 PayPal 的付費方式，若要升級請來信 <a href="mailto:support@macromicro.me">support@macromicro.me</a>，我們將盡快為您處理，謝謝！'
,"upgrade-prime:msg:confirm-upgrade":'確認要升級為 MM Prime?'
,"us-elections:biden":'拜登'
,"us-elections:btn:2020":'2020 政策比較'
,"us-elections:btn:2024":'2024 政策比較'
,"us-elections:democratic":'民主黨'
,"us-elections:harris":'賀錦麗'
,"us-elections:map:tooltip":'英文名稱：{point.name}<br>英文代碼：{point.postal-code}<br>中文名稱：{point.tc}<br>總投票數：{point.total}'
,"us-elections:not-yet":'尚未確定'
,"us-elections:swing":'搖擺州'
,"us-elections:tie":'平手'
,"us-elections:trump":'川普'
,"user:account-merge:btn:yes":'執行合併'
,"user:achievement:chart:desc":'其他用戶與你發佈的圖表互動，包含：瀏覽數、按讚數與收藏數'
,"user:binding:title":'社群綁定'
,"user:confirm:msg":'你好，為確保會員能順利收到來自 MacroMicro 的信件，請輸入目前使用的 Email 信箱，謝謝。'
,"user:courses:bookmarked":'課程收藏'
,"user:courses:browsed":'已瀏覽完成'
,"user:courses:cate":'課程標籤'
,"user:courses:cate:edit":'編輯課程標籤'
,"user:courses:not_completed":'尚未完成'
,"user:courses:purchased":'已購買'
,"user:courses:uncated":'未分類'
,"user:email-confirm:error":'請勿輸入重複的信箱'
,"user:email-did-you-mean":'會不會是 {did-you-mean} 呢?'
,"user:exchange:copy-discount:success":'折扣碼已複製成功'
,"user:exchange:identity:all":'所有會員專屬'
,"user:exchange:identity:all:text":'所有'
,"user:exchange:identity:member":'會員專屬'
,"user:exchange:identity:regular":'一般'
,"user:exchange:identity:subscribers":'訂閱會員專屬'
,"user:exchange:limit:multiple:course:1":'此項目限購買 %s 課程學員專屬，'
,"user:exchange:limit:multiple:course:2":'此項目限購買 %s ，任一課程學員專屬，'
,"user:exchange:limit:multiple:course:3":'點擊課程加入，即可使用！'
,"user:exchange:pop-up:login":'此項目限%s會員專屬，請先登入會員。'
,"user:exchange:pop-up:login:telegram":'請先登入才能加入 Telegram'
,"user:exchange:pop-up:no-permission":'很抱歉，您目前不符合領取資格。'
,"user:exchange:pop-up:subscribe":'此項目為%s，立即成為訂閱會員。'
,"user:exchange:pop-up:upgrade":'此項目限 %s 會員專屬，立即前往升級訂閱。'
,"user:exchange:videos":'，您可立即前往 %s 使用。'
,"user:invalid-email":'格式似乎錯了?'
,"user:logged-in:become-biz":'成為<a href=\"/subscribe\">企業會員</a>開啟此功能使用權限！'
,"user:logged-in:become-subscriber":'成為<a href=\"/subscribe\">訂閱會員</a>開啟此功能使用權限！'
,"user:login-as-subscriber":'若您已經是訂閱會員請<a href=\"/login\">點此登入</a>。'
,"user:max-only-content:normal":'成為 <a href=\"/subscribe\">MM Max</a> 開啟此功能使用權限！'
,"user:pls-login":'免費成為 MM 會員，瀏覽更多內容！'
,"user:pls-subscribe:charts":'成為<a href=\"/subscribe\">訂閱會員</a>享全站圖表無限瀏覽！'
,"user:pls-subscribe:charts2":'成為<a href=\"/subscribe\">訂閱會員</a>，解鎖此圖瀏覽！'
,"user:pls-subscribe:sector":'11/30 前升級 <a href=\"/subscribe\" data-trk4=\'{\"evt\":\"chart_micro\"}\'>MM Prime 年繳訂閱</a>，<br>解鎖瀏覽權限！'
,"user:pls-subscribe:sector-1216":'此為 MM Prime 年繳限定瀏覽'
,"user:pls-upgrade-to-pro":'已達本週圖表瀏覽上限，加入 MM PRO 即可無限閱讀全站總經圖表！12/31 前訂閱還可自動升級為 MM Prime 會員！'
,"user:prime-only-content:normal":'成為 <a href=\"/subscribe\">MM Prime</a> 開啟此功能使用權限！'
,"user:prime-only-content:pro":'升級 <a href=\"/user/upgrade/y/prime\">MM Prime</a> 開啟此功能使用權限！'
,"user:prime-only-content:unlogin":'成為 <a href=\"/subscribe\">MM Prime</a> 開啟此功能使用權限！若您已經是 MM Prime 請<a href=\"/login\">點此登入</a>。'
,"user:pro-only-content":'此內容/功能僅限 PRO 會員使用，12/31 前訂閱還可自動升級為 MM Prime 會員！'
,"user:reset-password:msg":'你好，請輸入新的密碼'
,"user:reset-password:title":'請重新設定密碼'
,"user:send-email:count":'{num} 秒後重新寄送'
,"user:send-email:error":'請勿重複寄信'
,"user:send-email:fail":'寄送失敗，請洽客服人員'
,"user:send-email:success":'寄送成功，請至信箱進行驗證'
,"user:settings:biz-contact:title":'企業專屬通道'
,"user:settings:biz-upgrade-msg":'升級 MM Business 方案，將能解鎖%s功能，<a target=\'_blank\' href=\'/subscribe#modal-biz-contact\' data-trk4=\'{\"evt\":\"user_settings_biz_contact\"}\'>立即聯絡專員了解</a>'
,"user:settings:btn:biz-contact-specialist":'立即聯絡專員了解'
,"user:settings:btn:cancel_confirm_freedays":'免費延長訂閱 20 天'
,"user:settings:btn:close":'關閉'
,"user:settings:btn:confirm-upgrade":'確定升級'
,"user:settings:btn:maybe-not":'再考慮一下'
,"user:settings:cancel_confirm_freedays:success":'恭喜您免費延長訂閱 20 天成功，續約到期日期為：%s。'
,"user:settings:cancel_confirm_msg":'很遺憾您正猶豫是否繼續使用 MM 訂閱服務，在您正式決定前，MM 特別提供一次性免費延長訂閱 20 天優惠，期待您能繼續與我們一起重視基本面，為自己的投資負責。'
,"user:settings:enter_email":'請輸入電子信箱'
,"user:settings:error:freedays":'每個帳號限免費延長一次。'
,"user:settings:error:freedays-1":'請先成為訂閱會員，才可免費延長20天。'
,"user:settings:sub_accounts:title":'管理團隊帳號'
,"user:settings:sure_cancel:post-prime-launch":'你確認要取消訂閱嗎？若取消訂閱你將無法終生享有 %s 價格。'
,"user:settings:txt:confirm-use-card-on-file":'確定要使用存檔信用卡 (後四碼: %s) 進行支付?'
,"user:subscriber-only-content":'成為<a href=\"/subscribe\">訂閱會員</a>開啟此功能使用權限！'
,"user:subscriber-only-content:unlogin":'成為 <a href=\"/subscribe\">訂閱會員</a> 開啟此功能使用權限！若您已經是訂閱會員請<a href=\"/login\">點此登入</a>。'
,"user:upgrade-max":'升級 <a href=\"/user/upgrade/y/max\">MM Max</a> 開啟此功能使用權限！'
,"user:upgrade:confirm":'確定要升級為'
,"user_info:againask:disabled":'追問已下架'
,"user_info:againask:disabled:reason1":'你參與回答的提問受檢舉，M平方審查後已下架此提問，追問尚未獲回答，系統已自動下架追問，並退還追問費 1 M幣'
,"user_info:againask:disabled:reason2":'由於你參與回答的提問被檢舉，M平方審查後已下架此提問，你的追問已同步下架'
,"user_info:againask:disabled:reason3":'你的提問已選出最佳回答，而追問逾期未獲回答，系統已自動下架追問，並退還追問費 1 M幣'
,"user_info:againask:disabled:reason4":'你的追問已超過懸賞時間且未得到回答，系統已自動下架追問，並退還 1 M幣'
,"user_info:againask:disabled:reason5":'由於你的追問被檢舉，原因為「{reason}」，M平方審查後已下架此追問，且將不退還追問費 1 M幣'
,"user_info:againask:empty":'無任何追問回答'
,"user_info:againask:total":'總共有 {total} 個追問回答'
,"user_info:all:question:tag":'所有提問'
,"user_info:answer:disabled":'回答已下架'
,"user_info:answer:disabled:reason1":'你參與的提問受檢舉，M平方審查後已下架此提問與回答'
,"user_info:answer:disabled:reason2":'你被選的最佳回答受檢舉，原因為「{reason}」，M平方審查後已下架，並收回賞金 {mcoin} M幣'
,"user_info:answer:disabled:reason3":'你被選為最佳回答的提問受檢舉，M平方審查後已下架此提問與回答'
,"user_info:answer:disabled:reason3:1":'，並收回賞金 {mcoin} M幣'
,"user_info:answer:disabled:reason4":'你的回答受檢舉，原因為「{reason}」，M平方審查後已下架'
,"user_info:answer:empty":'開始回答，成為 MM智囊團一員並獲取賞金吧！'
,"user_info:answer:empty:btn":'立即開始回答'
,"user_info:answer:total":'總共有 {total} 個回答'
,"user_info:chart:empty":'前往工具箱繪製，同步發表至用戶觀點獲取M幣'
,"user_info:chart:empty:btn":'立即發表圖表'
,"user_info:chart:search:result":'總共有 {total} 個圖表'
,"user_info:question:closed:empty":'尚無結束懸賞的提問'
,"user_info:question:disabled":'提問已下架'
,"user_info:question:disabled:reason1":'你的提問未得到任何回答，系統已下架此提問，並退還賞金 {bounty} M幣及上架費 {mcoin} M幣'
,"user_info:question:disabled:reason2":'由於你的提問被檢舉，原因為「{reason}」，M平方審查後已下架此提問，且將不退還賞金 {bounty} M幣及上架費 {mcoin} M幣'
,"user_info:question:edit:error":'該提問已有人回答，無法再次編輯'
,"user_info:question:empty":'提問懸賞 x 知識共享，讓最專業的總經社群力為你解答'
,"user_info:question:empty:btn":'立即發表提問'
,"user_info:question:ing:empty":'尚無正在懸賞的提問'
,"user_info:question:total":'總共有 {total} 個提問'
,"user_info:question:total:get:mcoin":'已獲得 <span class="badge badge-warning badge-pill mr-2">{mcoin} M幣</span>'
,"user_info:question:total:mcoin":'已花費 <span class="badge badge-warning badge-pill mr-2">{mcoin} M幣</span>'
,"user_info:search:answer:empty":'無任何回答'
,"user_info:search:chart:empty":'尚無發表中的圖表'
,"user_info:search:empty":'找不到符合的%s'
,"user_info:search:placeholder:againask":'搜尋提問標題'
,"user_info:search:placeholder:chart":'搜尋已發表圖表'
,"user_info:search:placeholder:question":'搜尋已發表提問'
,"user_info:search:question:empty":'找不到符合的提問，建議搜尋其他關鍵字'
,"user_info:sort:answer:created:new:old":'回答時間（由新到舊）'
,"user_info:sort:answer:created:old:new":'回答時間（由舊到新）'
,"user_info:sort:question:created:new:old":'提問時間（新到舊）'
,"user_info:sort:question:created:old:new":'提問時間（舊到新）'
,"video:btn:soldout":'銷售截止'
,"video:buy_video":'請先購買影片'
,"video:instructor":'講師'
,"video:length":'分鐘'
,"video:length_title":'課時'
,"video:mcoin":'M幣'
,"video:member:only":'訂閱會員專屬價'
,"video:student:msg":'人已購買'
,"video:watched:msg":'人已觀看'
,"view:sort:high:low":'瀏覽數（高到低）'
};